/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package decoration;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import static decoration.cust_payement.Tahoma;
import static decoration.project_contractor.Tahoma;
import static decoration.project_state.Tahoma;
import static decoration.project_state.fontSize;
import static decoration.res_details.Tahoma;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.*;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author salah
 */
public class all_project extends javax.swing.JFrame {

    /**
     * Creates new form all_project
     */
    public all_project() {
        Connection c=null;
       
        initComponents();
        this.setLocationRelativeTo(null);
        show_emp();
        combo_fill();
    }
     public static com.itextpdf.text.Font Tahoma = FontFactory.getFont("c://windows//fonts//tahoma.ttf",
                            BaseFont.IDENTITY_H,fontSize);
    public void close(){
        

        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEve­ntQueue().postEvent(winClosingEvent);
        
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        serial_search = new javax.swing.JTextField();
        name_search = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        e_name_compo = new javax.swing.JComboBox();
        c_name_txt = new javax.swing.JTextField();
        p_name_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        p_serial_txt = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        new_emp = new javax.swing.JButton();
        c_phone_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        e_serial_txt = new javax.swing.JLabel();
        proj_print = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        all_proj_jtable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 3), "بحث"));

        jLabel9.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jLabel9.setText("اسم المشروع");

        jLabel2.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jLabel2.setText("رقم المشروع");

        serial_search.setBackground(new java.awt.Color(255, 255, 153));
        serial_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serial_searchKeyReleased(evt);
            }
        });

        name_search.setBackground(new java.awt.Color(255, 255, 153));
        name_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                name_searchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serial_search)
                    .addComponent(name_search))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(name_search, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serial_search, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel8.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jLabel8.setText("اسم الموظف المسئول");

        e_name_compo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_name_compoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jLabel4.setText("رقم الموظف");

        jLabel5.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jLabel5.setText("اسم العميل");

        p_serial_txt.setBackground(new java.awt.Color(102, 255, 102));
        p_serial_txt.setText("...");

        jButton1.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\floppy_disk.jpg")); // NOI18N
        jButton1.setText("حفظ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 0));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\delete2.jpg")); // NOI18N
        jButton2.setText("حذف");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        new_emp.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        new_emp.setForeground(new java.awt.Color(0, 153, 0));
        new_emp.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\folder_new.jpg")); // NOI18N
        new_emp.setText("جديد");
        new_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_empActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jLabel6.setText("تليفون العميل");

        proj_print.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        proj_print.setForeground(new java.awt.Color(0, 153, 0));
        proj_print.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\document_text.jpg")); // NOI18N
        proj_print.setText("طباعه المشروع");
        proj_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proj_printActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jLabel7.setText("رقم المشروع");

        jLabel10.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jLabel10.setText("اسم المشروع");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p_name_txt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(c_name_txt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(c_phone_txt)
                            .addComponent(p_serial_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(e_name_compo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(e_serial_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(new_emp, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(proj_print, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_serial_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_phone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(e_serial_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_name_compo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(proj_print)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        all_proj_jtable.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        all_proj_jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        all_proj_jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                all_proj_jtableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(all_proj_jtable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 36, Short.MAX_VALUE))))
        );

        jScrollPane1.setViewportView(jPanel1);

        jMenu1.setText("File");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\printer.png")); // NOI18N
        jMenuItem3.setText("طباعه");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\close.png")); // NOI18N
        jMenuItem1.setText("اغلاق");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\exit.jpg")); // NOI18N
        jMenuItem2.setText("الخروج من البرنامج");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("تفاصيل");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setText("دفعات العميل");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setText("المقاولون");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setText("الخامات");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1273, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void all_proj_jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_all_proj_jtableMouseClicked
        // TODO add your handling code here:
        getting_data();
    }//GEN-LAST:event_all_proj_jtableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        insert_db();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void new_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_empActionPerformed
        // TODO add your handling code here:
        new_emp();
    }//GEN-LAST:event_new_empActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        del_emp();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void name_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name_searchKeyReleased
        // TODO add your handling code here:
        search_name();
    }//GEN-LAST:event_name_searchKeyReleased

    private void serial_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serial_searchKeyReleased
        // TODO add your handling code here:
        search_serial();
                
    }//GEN-LAST:event_serial_searchKeyReleased

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
//        print_all_data();
         MessageFormat header=new MessageFormat("Report print");
        MessageFormat footer=new MessageFormat("page{0, number,integer}");
        try{
            all_proj_jtable.print(JTable.PrintMode.FIT_WIDTH,header,footer);
             
              
              
        }catch(Exception e){JOptionPane.showMessageDialog(null,"حدث خطا اثناء الطباعه الرجاء المحاوله لاحقا والتاكد من الطابعه");}
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void proj_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proj_printActionPerformed
        // TODO add your handling code here:
        Document doc=new Document();

        String pserialt=p_serial_txt.getText();
        String namet=p_name_txt.getText();
        String cnamet=c_name_txt.getText();
        String cphonet=c_phone_txt.getText();
        String eserialt=e_serial_txt.getText();
        String e_namet=e_name_compo.getSelectedItem().toString();
        
         try{
            PdfWriter.getInstance(doc, new FileOutputStream("C:\\report\\all_project\\report.pdf"));
           // BaseFont bf1=BaseFont.createFont("C:\\Windows\\Fonts\\simpbdo.ttf", BaseFont.WINANSI, true);
            doc.open();
            Image img=Image.getInstance("C:\\report\\all_emp\\ModernDesignlogo.jpg");
            //img.setAbsolutePosition(30f, 700f);
            doc.add(img);
            PdfPTable headtable=new PdfPTable(1);
            headtable.setRunDirection(PdfWriter.RUN_DIRECTION_RTL);
            PdfPCell headcell=new PdfPCell();
            headcell.setBorder(Rectangle.NO_BORDER);
            
      
            PdfPCell preport=new PdfPCell(new Paragraph("التقرير",Tahoma));
           // cnamec.setBackgroundColor(BaseColor.YELLOW);
            preport.setHorizontalAlignment(Element.ALIGN_CENTER);
            preport.setBorder(Rectangle.NO_BORDER);
            headtable.addCell(preport);
            
           
            doc.add(headtable);
            
           // doc.add(new Paragraph());
            doc.add(new Paragraph("\n"));

            PdfPTable bodytable=new PdfPTable(2);
            bodytable.setRunDirection(PdfWriter.RUN_DIRECTION_RTL);
            PdfPCell bodycell=new PdfPCell();
           bodycell.setBorder(Rectangle.NO_BORDER);
           
            
            PdfPCell pserialar=new PdfPCell(new Paragraph("رقم المشروع",Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            pserialar.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(pserialar);
            
            
             PdfPCell pserialv=new PdfPCell(new Paragraph(pserialt,Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            pserialv.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(pserialv);
                        
          
             PdfPCell pnamear=new PdfPCell(new Paragraph("اسم المشروع",Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            pnamear.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(pnamear);
            
           
             PdfPCell pnamev=new PdfPCell(new Paragraph(namet,Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            pnamev.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(pnamev);

            
         
             PdfPCell cnamear=new PdfPCell(new Paragraph("اسم العميل",Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            cnamear.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(cnamear);
            
            
             PdfPCell cnamev=new PdfPCell(new Paragraph(cnamet,Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            cnamev.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(cnamev);
            
           
             PdfPCell cphonear=new PdfPCell(new Paragraph("تليفون العميل",Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            cphonear.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(cphonear);
            
           
             PdfPCell cphonev=new PdfPCell(new Paragraph(cphonet,Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            cphonev.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(cphonev);
                        
             
             PdfPCell eserialar=new PdfPCell(new Paragraph("رقم الموظف",Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            eserialar.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(eserialar);
            
            
             PdfPCell eserialv=new PdfPCell(new Paragraph(eserialt,Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            eserialv.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(eserialv);
                        
         
             PdfPCell enamear=new PdfPCell(new Paragraph("اسم الموظف المسئول",Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            enamear.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(enamear);
            
            
             PdfPCell enamev=new PdfPCell(new Paragraph(e_namet,Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            enamev.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(enamev);
                        
            //bodytable.addCell(bodycell);
            doc.add(bodytable);
            doc.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "برجاء اغلاق "
                    + "report.pdf");
        }
         
          if (Desktop.isDesktopSupported()) {
    try {
        File myFile = new File("C:\\report\\all_project\\report.pdf");
        Desktop.getDesktop().open(myFile);
    }
    catch (IOException ex) {
        JOptionPane.showMessageDialog(null, "لايمكن فتح "
                + "report.pdf");}
         }
        
    }//GEN-LAST:event_proj_printActionPerformed

    private void e_name_compoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_name_compoActionPerformed
        // TODO add your handling code here:
        Connection c= null;
        Statement s =null;
        String name=e_name_compo.getSelectedItem().toString();
        ResultSet rs = null;
        try{
            Class.forName("org.sqlite.JDBC");
              c = DriverManager.getConnection("jdbc:sqlite:decor.db");
              c.setAutoCommit(false);
              s=c.createStatement();
              String sql="select e_serial from emp where e_name='"+name+"'";
              rs=s.executeQuery(sql);
              if(rs.next()){
                  String eserial=rs.getString("e_serial");
                  e_serial_txt.setText(eserial);
              }
             s.close();
            c.commit();
            c.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "برجاء التاكد من قاعدة البيانات او اغلاق البرنامج وتشغيله");
           
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }//GEN-LAST:event_e_name_compoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        String pserial=p_serial_txt.getText();
        cust_payement pc=new cust_payement();        
        pc.pserial_txt.setText(this.p_serial_txt.getText());
        pc.proj_name.setText(this.p_name_txt.getText());  //project name      
        pc.cust_name.setText(this.c_name_txt.getText());// customer name
        pc.custphone_txt.setText(this.c_phone_txt.getText());//customer phone number
        pc.eserial_txt.setText(this.e_serial_txt.getText());//emplyee serial
        pc.ename_txt.setText(this.e_name_compo.getSelectedItem().toString()); // name of the respnsable emp
        if(pserial=="..."){
            JOptionPane.showMessageDialog(null, "من فضلك اختار مشروع من قائمه المشاريع");
        
        }else{
            pc.getting_data();
            pc.setVisible(true);
        }

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        String pserial=p_serial_txt.getText();
        project_contractor pc=new project_contractor();        
        pc.pserial_txt.setText(this.p_serial_txt.getText());
        pc.proj_name.setText(this.p_name_txt.getText());  //project name      
        pc.cust_name.setText(this.c_name_txt.getText());// customer name
        pc.custphone_txt.setText(this.c_phone_txt.getText());//customer phone number
        pc.eserial_txt.setText(this.e_serial_txt.getText());//emplyee serial
        pc.ename_txt.setText(this.e_name_compo.getSelectedItem().toString()); // name of the respnsable emp
        if(pserial=="..."){
            JOptionPane.showMessageDialog(null, "من فضلك اختار مشروع من قائمه المشاريع");
        
        }else{
            pc.show_details();
            pc.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        String pserial=p_serial_txt.getText();
        res_details pc=new res_details();        
        pc.pserial_txt.setText(this.p_serial_txt.getText());
        pc.proj_name.setText(this.p_name_txt.getText());  //project name      
        pc.cust_name.setText(this.c_name_txt.getText());// customer name
        pc.custphone_txt.setText(this.c_phone_txt.getText());//customer phone number
        pc.eserial_txt.setText(this.e_serial_txt.getText());//emplyee serial
        pc.ename_txt.setText(this.e_name_compo.getSelectedItem().toString()); // name of the respnsable emp
        if(pserial=="..."){
            JOptionPane.showMessageDialog(null, "من فضلك اختار مشروع من قائمه المشاريع");
        
        }else{
            pc.selecting_db();
            pc.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //this fu selects all employee data from DB
    public void show_emp(){
        Connection c=null;
        Statement s=null;
        
        try{
              Class.forName("org.sqlite.JDBC");
              c = DriverManager.getConnection("jdbc:sqlite:decor.db");
              c.setAutoCommit(false);
              s=c.createStatement();
              
              String sql="select P_serial as 'رقم المشروع',p_name as 'اسم المشروع',c_name as 'اسم العميل', c_phone as 'رقم تليفون العميل'"+
                      ",e_serial as 'رقم الموظف', e_name as 'اسم الموظف' "+
                      "from project";
              all_proj_jtable.setModel(DbUtils.resultSetToTableModel(s.executeQuery(sql)));
              s.close();
              c.commit();
              c.close();
              
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"خطأ!!!"
                    + "برجاء المحاوله مره اخرى");
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }
    
    //getting data from jtable to jtext field and jlabel
    public void getting_data(){
        //connecting to DB
        Connection c= null;
        PreparedStatement pst=null;
        ResultSet rs=null;
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            int row=all_proj_jtable.getSelectedRow();
            String serial=(all_proj_jtable.getModel().getValueAt(row, 0).toString());
            String sql="select * from project where p_serial="+serial+"";
            pst=(PreparedStatement) c.prepareStatement(sql);
            rs=pst.executeQuery(); 
            if(rs.next()){
                String serialt=rs.getString("p_serial");
                p_serial_txt.setText(serialt);
                
                String namet=rs.getString("p_name");
                p_name_txt.setText(namet);
                
                String cnamet=rs.getString("c_name");
                c_name_txt.setText(cnamet);
                
                String phonet=rs.getString("c_phone");
                c_phone_txt.setText(phonet);
                
                String eserialt=rs.getString("e_serial");
                e_serial_txt.setText(eserialt);
                
             
                
                String enamet=rs.getString("e_name");
                 e_name_compo.setSelectedItem(enamet);
            }
            rs.close();
              pst.close();
              c.commit();
              c.close();
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"لايمكن القيام بالعمليه");
        }
         finally{
            try{
               
          //  rs.close();
            pst.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }
    
    //combo box fill
    public void combo_fill(){
        Connection c=null;
        Statement s=null;
        ResultSet rs=null;
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            String sql="select e_name from emp;";
            rs=s.executeQuery(sql);
            while(rs.next()){
                String pname =rs.getString("e_name");
                e_name_compo.addItem(pname);
               
            }
             s.close();
              c.commit();
              c.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"برجاء التاكد من قاعده البيانات او اغلاق وتشغيل البرنامج");
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }
    //insert employee id to database
    public void insert_db(){
        Connection c=null;
        Statement s=null;
        ResultSet rs=null;
        String namet=p_name_txt.getText();
        String cnamet=c_name_txt.getText();
        String cphonet=c_phone_txt.getText();
        String eserialt=e_serial_txt.getText();
        String e_namet=e_name_compo.getSelectedItem().toString();
        String eserial=null;
        String st=p_serial_txt.getText();
        
        
        try{
           Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            //insert new
            if(st=="..."){
                Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            String sql_pname="select p_name from project where p_name='"+namet+"'";
            rs=s.executeQuery(sql_pname);
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "هذا المشروع مسجل مسبقا.. برجاء التاكد من اسم المشروع ");
            }else{
            String sql1="select e_serial from emp where e_name='"+e_namet+"';";
            rs=s.executeQuery(sql1);
             while(rs.next())
            {
                 eserial=rs.getString(1);
            }
            
            String sql="insert into project(p_name,c_name,c_phone,e_serial,e_name)"+
                               " values('"+namet+"','"+cnamet+"','"+cphonet+"',"+eserial+",'"+e_namet+"');";
            s.executeUpdate(sql);
            String sql_update_emp="update emp set p_name='"+namet+"' where e_serial="+eserialt+"";
            s.executeUpdate(sql_update_emp);
             rs.close();

            s.close();
            c.commit();
            c.close();
            show_emp();
            }
            }else{
                                //update existing client

                Class.forName("org.sqlite.JDBC");
                c = DriverManager.getConnection("jdbc:sqlite:decor.db");
                c.setAutoCommit(false);
                s=c.createStatement();
                String sql_update="update project "
                        + "set p_name='"+namet+"',c_name='"+cnamet+"', c_phone='"+cphonet+"', e_serial="+eserialt+""
                        + ", e_name='"+e_namet+"'"
                        + "where p_serial="+st+";";
                s.executeUpdate(sql_update);
                 s.close();
                c.commit();
                 c.close();
                 Class.forName("org.sqlite.JDBC");
                c = DriverManager.getConnection("jdbc:sqlite:decor.db");
                c.setAutoCommit(false);
                s=c.createStatement();
                String sql_update_emp="update emp set p_name='"+namet+"',p_serial="+st+" where e_serial="+eserialt+"";
                s.executeUpdate(sql_update_emp);
                
            s.close();
            c.commit();
            c.close();
            show_emp();
            
            }
                     
            
           // s.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"هذا المشروع مسجل مسبقا.. برجاء التاكد من اسم المشروع ");
        }
        finally{
            try{
               
            //rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
        }
    }
    
    //empty jtext fields to insert new employee
    public void new_emp(){
        try{
            p_serial_txt.setText("...");
            p_name_txt.setText(null);
            c_name_txt.setText(null);
            c_phone_txt.setText(null);
            e_serial_txt.setText(null);

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"error:"+e);
        }
    }
    //delete employee
    public void del_emp(){
        Connection c= null;
        Statement s=null;
        String pserialt=p_serial_txt.getText();
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            String sql_del="delete from project where p_serial="+pserialt+";";
            String sql_del_project_details="delete from project_details where p_serial="+pserialt+"";
            String sql_del_con="delete from proj_contractor where p_serial="+pserialt+"";
            String sql_del_cd="delete from cont_date where p_serial="+pserialt+" ";
            String sql_del_cp="delete from cust_payed where p_serial="+pserialt+" ";
            String sql_dc="delete from cust_payed_date where p_serial="+pserialt+" ";
            String sql_dr="delete from details_res where p_serial="+pserialt+" ";
            
            

            s.executeUpdate(sql_del);
            s.executeUpdate(sql_del_project_details);
            s.executeUpdate(sql_del_con);
            s.executeUpdate(sql_del_cd);
            s.executeUpdate(sql_del_cp);
            s.executeUpdate(sql_dc);
            s.executeUpdate(sql_dr);
            s.close();
            c.commit();
            c.close();
            show_emp();
            new_emp();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"لايمكن حزف المشروع برجاء المحاوله لاحقا");
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }
    //search by name 
    public void search_name(){
         Connection c= null;
        Statement s=null;
       // ResultSet rs=null;
        String names=name_search.getText();
        String serials=serial_search.getText();
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            String sql="select P_serial as 'رقم المشروع',p_name as 'اسم المشروع',c_name as 'اسم العميل', c_phone as 'رقم تليفون العميل',e_serial as 'رقم الموظف', e_name as 'اسم الموظف' from project where p_serial like '%"+serials+"%' and p_name like '%"+names+"%'";         
       
            s.executeQuery(sql); 
            all_proj_jtable.setModel(DbUtils.resultSetToTableModel(s.executeQuery(sql)));
              s.close();
              c.commit();
              c.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "خطأ");
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
            
       
    }
    
    //search by emp serial number 
    public void search_serial(){
          Connection c= null;
        Statement s=null;
       // ResultSet rs=null;
        String serials=serial_search.getText();
        String names=name_search.getText();
        try{
             Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            String sql="select P_serial as 'رقم المشروع',p_name as 'اسم المشروع',c_name as 'اسم العميل', c_phone as 'رقم تليفون العميل',e_serial as 'رقم الموظف', e_name as 'اسم الموظف' from project where p_serial like '%"+serials+"%' and p_name like '%"+names+"%'";         
            s.executeQuery(sql); 
            all_proj_jtable.setModel(DbUtils.resultSetToTableModel(s.executeQuery(sql)));
              s.close();
              c.commit();
              c.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "خطأ!! ");
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }
    
    //print all table data 
    public void print_all_data(){
        Connection c=null;
        Statement s=null;
        ResultSet rs=null;
        Document doc=new Document();
        try{
            PdfWriter.getInstance(doc, new FileOutputStream("C:\\report\\all_project\\all\\report.pdf"));
            doc.open();
            PdfPTable headtable=new PdfPTable(1);
            headtable.setRunDirection(PdfWriter.RUN_DIRECTION_RTL);
            PdfPCell headcell=new PdfPCell();
            headcell.setBorder(Rectangle.NO_BORDER);
            Paragraph preport;
            preport= new Paragraph("المشاريع\n" ,Tahoma);
            preport.setAlignment(PdfPCell.ALIGN_LEFT);
            headcell.setHorizontalAlignment(Element.ALIGN_CENTER);
            headcell.addElement(preport);
            
            headtable.addCell(headcell);
            doc.add(headtable);
            
            doc.add(new Paragraph("\n"));
            
            PdfPTable dettbl=new PdfPTable(6);
            dettbl.setRunDirection(PdfWriter.RUN_DIRECTION_RTL);
            PdfPCell detcell=new PdfPCell();
            detcell.setBorder(Rectangle.NO_BORDER);
            
         
            PdfPCell projnumar=new PdfPCell(new Paragraph("رقم المشروع",Tahoma));
           // projnumar.setBorder(Rectangle.NO_BORDER);
            projnumar.setHorizontalAlignment(Element.ALIGN_CENTER);
            projnumar.setBackgroundColor(BaseColor.YELLOW);
            dettbl.addCell(projnumar);
            
         
            PdfPCell projnamear=new PdfPCell(new Paragraph("اسم المشروع",Tahoma));
           // projnamear.setBorder(Rectangle.NO_BORDER);
            projnamear.setHorizontalAlignment(Element.ALIGN_CENTER);
            projnamear.setBackgroundColor(BaseColor.YELLOW);
            dettbl.addCell(projnamear);
            
           
            PdfPCell cust_namrar=new PdfPCell(new Paragraph("اسم العميل",Tahoma));
           // cust_namrar.setBorder(Rectangle.NO_BORDER);
            cust_namrar.setHorizontalAlignment(Element.ALIGN_CENTER);
            cust_namrar.setBackgroundColor(BaseColor.YELLOW);
            dettbl.addCell(cust_namrar);
            
           
            PdfPCell cust_numar=new PdfPCell(new Paragraph("رقم تليفون العميل",Tahoma));
           // cust_numar.setBorder(Rectangle.NO_BORDER);
            cust_numar.setHorizontalAlignment(Element.ALIGN_CENTER);
            cust_numar.setBackgroundColor(BaseColor.YELLOW);
            dettbl.addCell(cust_numar);
            
           
            PdfPCell empnumar=new PdfPCell(new Paragraph("رقم الموظف" ,Tahoma));
           // empnumar.setBorder(Rectangle.NO_BORDER);
            empnumar.setHorizontalAlignment(Element.ALIGN_CENTER);
            empnumar.setBackgroundColor(BaseColor.YELLOW);
            dettbl.addCell(empnumar);
            
           
            PdfPCell empnamear=new PdfPCell(new Paragraph("اسم الموظف" ,Tahoma));
           // empnamear.setBorder(Rectangle.NO_BORDER);
            empnamear.setHorizontalAlignment(Element.ALIGN_CENTER);
            empnamear.setBackgroundColor(BaseColor.YELLOW);
            dettbl.addCell(empnamear);
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            String sql_select="select * from project";
            rs=s.executeQuery(sql_select);
            while(rs.next()){
                String pserialt=rs.getString("p_serial");
                PdfPCell pserialtp=new PdfPCell(new Paragraph(pserialt ,Tahoma));
          //  pserialtp.setBorder(Rectangle.NO_BORDER);
                pserialtp.setHorizontalAlignment(Element.ALIGN_CENTER);
           // pserialtp.setBackgroundColor(BaseColor.YELLOW);
                dettbl.addCell(pserialtp);
            
                String pnamet=rs.getString("p_name");
                PdfPCell pnametp=new PdfPCell(new Paragraph(pnamet ,Tahoma));
           // pnametp.setBorder(Rectangle.NO_BORDER);
            pnametp.setHorizontalAlignment(Element.ALIGN_CENTER);
         //   pnametp.setBackgroundColor(BaseColor.YELLOW);
            dettbl.addCell(pnametp);
            
                String cnamet=rs.getString("c_name");
                PdfPCell cnametp=new PdfPCell(new Paragraph(cnamet ,Tahoma));
         //   empnamear.setBorder(Rectangle.NO_BORDER);
            cnametp.setHorizontalAlignment(Element.ALIGN_CENTER);
           // empnamear.setBackgroundColor(BaseColor.YELLOW);
            dettbl.addCell(cnametp);
            
                String cnamept=rs.getString("c_phone");
                PdfPCell cnameptp=new PdfPCell(new Paragraph(cnamept ,Tahoma));
        //    empnamear.setBorder(Rectangle.NO_BORDER);
            cnameptp.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  empnamear.setBackgroundColor(BaseColor.YELLOW);
            dettbl.addCell(cnameptp);
            
                String eserialt=rs.getString("e_serial");
                PdfPCell eserialtp=new PdfPCell(new Paragraph(eserialt,Tahoma));
         //   empnamear.setBorder(Rectangle.NO_BORDER);
            eserialtp.setHorizontalAlignment(Element.ALIGN_CENTER);
           // empnamear.setBackgroundColor(BaseColor.YELLOW);
            dettbl.addCell(eserialtp);
            
                String enamet=rs.getString("e_name");
                PdfPCell enametp=new PdfPCell(new Paragraph(enamet ,Tahoma));
            //empnamear.setBorder(Rectangle.NO_BORDER);
            enametp.setHorizontalAlignment(Element.ALIGN_CENTER);
            //empnamear.setBackgroundColor(BaseColor.YELLOW);
            dettbl.addCell(enametp);
            }
            
            doc.add(dettbl);
             doc.close(); 
            rs.close();
            s.close();
            c.commit();
            c.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
                rs.close();
                s.close();
                c.commit();
                c.close();
            }catch(Exception e){}
        }
          if (Desktop.isDesktopSupported()) {
    try {
        File myFile = new File("C:\\report\\all_project\\all\\report.pdf");
        Desktop.getDesktop().open(myFile);
    }
    catch (IOException ex) {
        JOptionPane.showMessageDialog(null, "لايمكن فتح "
                + "report.pdf");}
         }
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(all_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(all_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(all_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(all_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new all_emp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable all_proj_jtable;
    public static javax.swing.JTextField c_name_txt;
    public static javax.swing.JTextField c_phone_txt;
    public static javax.swing.JComboBox e_name_compo;
    public static javax.swing.JLabel e_serial_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField name_search;
    private javax.swing.JButton new_emp;
    public static javax.swing.JTextField p_name_txt;
    public static javax.swing.JLabel p_serial_txt;
    private javax.swing.JButton proj_print;
    private javax.swing.JTextField serial_search;
    // End of variables declaration//GEN-END:variables
}
