/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package decoration;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import static decoration.project_state.Tahoma;
import static decoration.project_state.fontSize;
import static decoration.res_details.Tahoma;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.*;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author salah
 */
public class all_emp extends javax.swing.JFrame {

    /**
     * Creates new form all_emp
     */
    public all_emp() {
        initComponents();
        this.setLocationRelativeTo(null);
        show_emp();
        combo_fill();
    }
    public static com.itextpdf.text.Font Tahoma = FontFactory.getFont("c://windows//fonts//tahoma.ttf",
                            BaseFont.IDENTITY_H,fontSize);
    public void close(){
        

        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEve­ntQueue().postEvent(winClosingEvent);
        
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        serial_search = new javax.swing.JTextField();
        name_search = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        p_name_compo = new javax.swing.JComboBox();
        e_inventory_txt = new javax.swing.JTextField();
        e_age_txt = new javax.swing.JTextField();
        e_phone_txt = new javax.swing.JTextField();
        e_name_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        e_serial_txt = new javax.swing.JLabel();
        e_salary_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        new_emp = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        all_emp_jtable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 3), "بحث"));

        serial_search.setBackground(new java.awt.Color(255, 255, 102));
        serial_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serial_searchActionPerformed(evt);
            }
        });
        serial_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serial_searchKeyReleased(evt);
            }
        });

        name_search.setBackground(new java.awt.Color(255, 255, 102));
        name_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                name_searchKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel9.setText("الاسم");

        jLabel2.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel2.setText("رقم الموظف");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serial_search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_search, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serial_search, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel8.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel8.setText("اسم المشروع");

        jLabel4.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel4.setText("رقم الهاتف");

        jLabel5.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel5.setText("العمر");

        jLabel7.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel7.setText("العهدة");

        e_serial_txt.setBackground(new java.awt.Color(102, 255, 102));
        e_serial_txt.setText("...");

        jLabel6.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel6.setText("المرتب");

        jButton1.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\floppy_disk.jpg")); // NOI18N
        jButton1.setText("حفظ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 0));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\delete2.jpg")); // NOI18N
        jButton2.setText("حذف");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        new_emp.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        new_emp.setForeground(new java.awt.Color(0, 153, 0));
        new_emp.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\folder_new.jpg")); // NOI18N
        new_emp.setText("جديد");
        new_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_empActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 0));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\document_text.jpg")); // NOI18N
        jButton3.setText("طباعه بيانات موظف");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel10.setText("رقم الموظف");

        jLabel11.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel11.setText("الاسم");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(e_phone_txt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(e_age_txt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(e_name_txt)
                            .addComponent(e_serial_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(e_salary_txt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(e_inventory_txt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p_name_compo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(new_emp, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_serial_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_age_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_phone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_salary_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_inventory_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_name_compo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jButton3))
        );

        all_emp_jtable.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        all_emp_jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        all_emp_jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                all_emp_jtableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(all_emp_jtable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\printer.png")); // NOI18N
        jMenuItem2.setText("طباعه");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\close.png")); // NOI18N
        jMenuItem1.setText("اغلاق");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\exit.jpg")); // NOI18N
        jMenuItem3.setText("الخروج من البرنامج");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1212, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void all_emp_jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_all_emp_jtableMouseClicked
        // TODO add your handling code here:
        getting_data();
    }//GEN-LAST:event_all_emp_jtableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        insert_db();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void new_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_empActionPerformed
        // TODO add your handling code here:
        new_emp();
    }//GEN-LAST:event_new_empActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        del_emp();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void serial_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serial_searchKeyReleased
        // TODO add your handling code here:
        search_serial();
    }//GEN-LAST:event_serial_searchKeyReleased

    private void name_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name_searchKeyReleased
        // TODO add your handling code here:
        search_name();
    }//GEN-LAST:event_name_searchKeyReleased
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String eserialt=e_serial_txt.getText();
        String namet=e_name_txt.getText();
        String aget=e_age_txt.getText();
        String phonet=e_phone_txt.getText();
        String salaryt=e_salary_txt.getText();
        String inventoryt=e_inventory_txt.getText();
        String p_namet=p_name_compo.getSelectedItem().toString();
        
            
        Document doc=new Document();
        
         try{
            PdfWriter.getInstance(doc, new FileOutputStream("C:\\report\\all_emp\\report.pdf"));
           // BaseFont bf1=BaseFont.createFont("C:\\Windows\\Fonts\\simpbdo.ttf", BaseFont.WINANSI, true);
            doc.open();
            
            Image img=Image.getInstance("C:\\report\\all_emp\\ModernDesignlogo.jpg");
            //img.setAbsolutePosition(30f, 700f);
            doc.add(img);
            PdfPTable headtable=new PdfPTable(1);
            headtable.setRunDirection(PdfWriter.RUN_DIRECTION_RTL);
            PdfPCell headcell=new PdfPCell();
            headcell.setBorder(Rectangle.NO_BORDER);
            
            
            PdfPCell preport=new PdfPCell(new Paragraph("التقرير\n",Tahoma));
           // cnamec.setBackgroundColor(BaseColor.YELLOW);
            preport.setHorizontalAlignment(Element.ALIGN_CENTER);
            preport.setBorder(Rectangle.NO_BORDER);
            headtable.addCell(preport);
            doc.add(headtable);
            
//            Paragraph datereport;
//            datereport= new Paragraph(new java.util.Date().toString() ,Tahoma);
//            datereport.setAlignment(PdfPCell.ALIGN_LEFT);
//            headcell.addElement(datereport);
//            headtable.addCell(headcell);
//            doc.add(headtable);
            
            doc.add(new Paragraph("\n"));
           // doc.add(new Paragraph("------------------------------------------------------------------------------------------------------------------------------"));

            PdfPTable bodytable=new PdfPTable(2);
            bodytable.setRunDirection(PdfWriter.RUN_DIRECTION_RTL);
            PdfPCell bodycell=new PdfPCell();
           bodycell.setBorder(Rectangle.NO_BORDER);
           
           
           
          
            PdfPCell eserialar=new PdfPCell(new Paragraph("رقم الموظف",Tahoma));
            eserialar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  eserialar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(eserialar);
            
            
            PdfPCell eserialv=new PdfPCell(new Paragraph(eserialt,Tahoma));
            eserialv.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  eserialv.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(eserialv);
                        
            
             PdfPCell enamear=new PdfPCell(new Paragraph("اسم الموظف",Tahoma));
            enamear.setHorizontalAlignment(Element.ALIGN_CENTER);
           // enamear.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(enamear);
            
            
             PdfPCell enamev=new PdfPCell(new Paragraph(namet,Tahoma));
            enamev.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  enamev.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(enamev);

            
           
             PdfPCell agear=new PdfPCell(new Paragraph("العمر",Tahoma));
            agear.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  agear.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(agear);
            
            
             PdfPCell agev=new PdfPCell(new Paragraph(aget,Tahoma));
            agev.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  agev.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(agev);
            
                        
           
             PdfPCell ephonear=new PdfPCell(new Paragraph("رقم الهاتف ",Tahoma));
            ephonear.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  ephonear.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(ephonear);
            
           
             PdfPCell ephonev=new PdfPCell(new Paragraph(phonet,Tahoma));
            ephonev.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  ephonev.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(ephonev);
                        
                        
            
             PdfPCell esalaryar=new PdfPCell(new Paragraph("المرتب" ,Tahoma));
            esalaryar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  esalaryar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(esalaryar);
            
            
             PdfPCell esalaryv=new PdfPCell(new Paragraph(salaryt,Tahoma));
            esalaryv.setHorizontalAlignment(Element.ALIGN_CENTER);
           // esalaryv.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(esalaryv);
                        
           
             PdfPCell inventoryar=new PdfPCell(new Paragraph("العهدة",Tahoma));
            inventoryar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  eserialv.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(inventoryar);
            
          
             PdfPCell inventoryv=new PdfPCell(new Paragraph(inventoryt,Tahoma));
            inventoryv.setHorizontalAlignment(Element.ALIGN_CENTER);
           // inventoryv.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(inventoryv);
            
          
             PdfPCell pnamear=new PdfPCell(new Paragraph("اسم المشروع",Tahoma));
            pnamear.setHorizontalAlignment(Element.ALIGN_CENTER);
         //   pnamear.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(pnamear);
            
            
             PdfPCell pnamev=new PdfPCell(new Paragraph(p_namet,Tahoma));
            pnamev.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  pnamev.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(pnamev);
                        
            //bodytable.addCell(bodycell);
            doc.add(bodytable);
            doc.close();
        }catch(Exception e){JOptionPane.showMessageDialog(null, "برجاء اغلاق "
                + "report.pdf");}
         
          if (Desktop.isDesktopSupported()) {
    try {
        File myFile = new File("C:\\report\\all_emp\\report.pdf");
        Desktop.getDesktop().open(myFile);
    }
    catch (IOException ex) {
        JOptionPane.showMessageDialog(null, "لايمكن فتح  "
                + "report.pdf");}
         }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        MessageFormat header=new MessageFormat("Report print");
        MessageFormat footer=new MessageFormat("page{0, number,integer}");
        try{
            all_emp_jtable.print(JTable.PrintMode.FIT_WIDTH,header,footer);
             
              
              
        }catch(Exception e){JOptionPane.showMessageDialog(null,"خطأ اثناء الطباعه برجاء التاكد من الطابعه");}
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void serial_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serial_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serial_searchActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //this fu selects all employee data from DB
    public void show_emp(){
        Connection c=null;
        Statement s=null;
        
        try{
              Class.forName("org.sqlite.JDBC");
              c = DriverManager.getConnection("jdbc:sqlite:decor.db");
              c.setAutoCommit(false);
              s=c.createStatement();
              
              String sql="select e_serial as 'رقم الموظف',e_name as 'الاسم',e_age as 'العمر'"+
                      ",e_phone as 'رقم الهاتف', e_salary as 'المرتب',e_inventory as 'العهده',p_name as 'المشروع' "+
                      "from emp";
              all_emp_jtable.setModel(DbUtils.resultSetToTableModel(s.executeQuery(sql)));
              s.close();
              c.commit();
              c.close();
              
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"برجاء التاكد من قاعده البيانات "
                    + "لايمكن القيام بالعمليه");
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }
    
    //getting data from jtable to jtext field and jlabel
    public void getting_data(){
        //connecting to DB
        Connection c= null;
        PreparedStatement pst=null;
        ResultSet rs=null;
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            int row=all_emp_jtable.getSelectedRow();
            String serial=(all_emp_jtable.getModel().getValueAt(row, 0).toString());
            String sql="select * from emp where e_serial="+serial+"";
            pst=(PreparedStatement) c.prepareStatement(sql);
            rs=pst.executeQuery(); 
            if(rs.next()){
                String serialt=rs.getString("e_serial");
                e_serial_txt.setText(serialt);
                
                String namet=rs.getString("e_name");
                e_name_txt.setText(namet);
                
                String aget=rs.getString("e_age");
                e_age_txt.setText(aget);
                
                String phonet=rs.getString("e_phone");
                e_phone_txt.setText(phonet);
                
                String salaryt=rs.getString("e_salary");
                e_salary_txt.setText(salaryt);
                
                String inventoryt=rs.getString("e_inventory");
                e_inventory_txt.setText(inventoryt);
                
                String pnamet=rs.getString("p_name");
                 p_name_compo.setSelectedItem(pnamet);
            }
              pst.close();
              rs.close();
              c.commit();
              c.close();
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"خطأ !!!"
                    + "الرجاء المحاوله مره اخرى");
        }
         finally{
            try{
               
          //  rs.close();
            pst.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }
    
    //combo box fill
    public void combo_fill(){
        Connection c=null;
        Statement s=null;
        ResultSet rs=null;
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            String sql="select p_name from project;";
            rs=s.executeQuery(sql);
            while(rs.next()){
                String pname =rs.getString("p_name");
                p_name_compo.addItem(pname);
               
            }
             s.close();
              c.commit();
              c.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"برجاء التأكد من قاعدة البيانات او اغلاق البرنامج وتشغيله");
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }
    //insert employee id to database
    public void insert_db(){
        Connection c=null;
        Statement s=null;
        ResultSet rs=null;
        String namet=e_name_txt.getText();
        String aget=e_age_txt.getText();
        String phonet=e_phone_txt.getText();
        String salaryt=e_salary_txt.getText();
        String inventoryt=e_inventory_txt.getText();
        String p_namet=p_name_compo.getSelectedItem().toString();
        String pserialt=null;
        String st=e_serial_txt.getText();
        
        
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            //insert new
            if(st=="..."){
                Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            String sql_ename="select e_name from emp where e_name = '"+namet+"'";
            rs=s.executeQuery(sql_ename);
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "لقد تم ادخل هذا الموظف سابقابرجاء التاكد من اسم الموظف");
                rs.close();
                s.close();
                c.commit();
                c.close();
            }else{
            String sql1="select p_serial from project where p_name='"+p_namet+"';";
            rs=s.executeQuery(sql1);
             while(rs.next())
            {
                 pserialt=rs.getString(1);
            }
            
            String sql="insert into emp(e_name,e_age,e_phone,e_salary,e_inventory,p_serial,p_name)"+
                               " values('"+namet+"',"+aget+",'"+phonet+"',"+salaryt+",'"+inventoryt+"',"+pserialt+",'"+p_namet+"');";
            s.executeUpdate(sql);
             rs.close();

            s.close();
            c.commit();
            c.close();
            show_emp();
            }
            }else{
                                //update existing client

                Class.forName("org.sqlite.JDBC");
                c = DriverManager.getConnection("jdbc:sqlite:decor.db");
                c.setAutoCommit(false);
                s=c.createStatement();
             
                String sql_update="update emp "
                        + "set e_name='"+namet+"',e_age="+aget+", e_phone='"+phonet+"', e_salary="+salaryt+", e_inventory='"+inventoryt+"', p_serial="+pserialt+""
                        + ", p_name='"+p_namet+"'"
                        + "where e_serial="+st+";";
                s.executeUpdate(sql_update);
                
            s.close();
            c.commit();
            c.close();
            show_emp();
            }
            
                       
            
           // s.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"لقد تم ادخل هذا الموظف سابقابرجاء التاكد من اسم الموظف");
        }
        finally{
            try{
               
           //rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
        }
        
    }
    
    //empty jtext fields to insert new employee
    public void new_emp(){
        try{
            e_serial_txt.setText("...");
            e_name_txt.setText(null);
            e_age_txt.setText(null);
            e_inventory_txt.setText(null);
            e_phone_txt.setText(null);
            e_salary_txt.setText(null);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"لايمكن القيام بالعمليه");
        }
    }
    //delete employee
    public void del_emp(){
        Connection c= null;
        Statement s=null;
        String serialt=e_serial_txt.getText();
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            String sql_del="delete from emp where e_serial="+serialt+";";
            
            s.executeUpdate(sql_del);
            
            s.close();
            c.commit();
            c.close();
            show_emp();
            new_emp();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"لايمكن حزف الموظف");
            
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }
    //search by name 
    public void search_name(){
         Connection c= null;
        Statement s=null;
       // ResultSet rs=null;
        String names=name_search.getText();
        String serials=serial_search.getText();
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            String sql="select e_serial as 'رقم الموظف',e_name as 'الاسم',e_age as 'العمر'"+
                      ",e_phone as 'رقم الهاتف', e_salary as 'المرتب',e_inventory as 'العهده',p_name as 'المشروع' "+
                      "from emp "
                    + "where e_name like '%"+names+"%' and e_serial like '%"+serials+"%'";           
            s.executeQuery(sql); 
            all_emp_jtable.setModel(DbUtils.resultSetToTableModel(s.executeQuery(sql)));
              s.close();
              c.commit();
              c.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "خطأ !!!");
        }
             finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
       
    }
    
    //search by emp serial number 
    public void search_serial(){
          Connection c= null;
        Statement s=null;
       // ResultSet rs=null;
        String serials=serial_search.getText();
        String names=name_search.getText();
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            String sql="select e_serial as 'رقم الموظف',e_name as 'الاسم',e_age as 'العمر'"+
                      ",e_phone as 'رقم الهاتف', e_salary as 'المرتب',e_inventory as 'العهده',p_name as 'المشروع' "+
                      "from emp "
                    + "where e_serial like '%"+serials+"%' and e_name like '%"+names+"%'";           
            s.executeQuery(sql); 
            all_emp_jtable.setModel(DbUtils.resultSetToTableModel(s.executeQuery(sql)));
              s.close();
              c.commit();
              c.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "خطأ!!!");
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(all_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(all_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(all_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(all_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new all_emp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable all_emp_jtable;
    private javax.swing.JTextField e_age_txt;
    private javax.swing.JTextField e_inventory_txt;
    private javax.swing.JTextField e_name_txt;
    private javax.swing.JTextField e_phone_txt;
    private javax.swing.JTextField e_salary_txt;
    private javax.swing.JLabel e_serial_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField name_search;
    private javax.swing.JButton new_emp;
    private javax.swing.JComboBox p_name_compo;
    private javax.swing.JTextField serial_search;
    // End of variables declaration//GEN-END:variables
}
