/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package decoration;

import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import static decoration.all_project.Tahoma;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author salah
 */
public class cust_report extends javax.swing.JFrame {

    /**
     * Creates new form cust_report
     */
    public cust_report() {
        initComponents();
        this.setLocationRelativeTo(null);
        combo_fill();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pserial_combo = new javax.swing.JComboBox();
        cust_name_txt = new javax.swing.JLabel();
        proj_name_txt = new javax.swing.JLabel();
        sum_cust_txt = new javax.swing.JLabel();
        cust_phone_txt = new javax.swing.JLabel();
        sum_res_txt = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("رقم المشروع");

        jLabel2.setText("اسم المشروع");

        jLabel3.setText("اسم العميل");

        jLabel4.setText("تليفون العميل");

        jLabel5.setText("مجموع دفعات العميل");

        jLabel6.setText("تكلفة الخامات");

        pserial_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pserial_comboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sum_res_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cust_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pserial_combo, 0, 137, Short.MAX_VALUE)
                                .addComponent(cust_phone_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sum_cust_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(proj_name_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pserial_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(proj_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cust_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cust_phone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sum_cust_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sum_res_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\printer.png")); // NOI18N
        jMenuItem1.setText("طباعه");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\close.png")); // NOI18N
        jMenuItem2.setText("اغلاق");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void close(){
        

        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEve­ntQueue().postEvent(winClosingEvent);
     }
    private void pserial_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pserial_comboActionPerformed
        // TODO add your handling code here:
                Connection c= null;
        Statement s= null;
        ResultSet rs=null;
        String pserialt=pserial_combo.getSelectedItem().toString();
        try {
            Class.forName("org.sqlite.JDBC");
              c = DriverManager.getConnection("jdbc:sqlite:decor.db");
              c.setAutoCommit(false);
              s=c.createStatement();
              String sql="select p_name, c_name,c_phone from project where p_serial="+pserialt+"";
              rs=s.executeQuery(sql);
              if(rs.next()){
                String pnamet=rs.getString("p_name");
                proj_name_txt.setText(pnamet);
                
                String cnamet=rs.getString("c_name");
                cust_name_txt.setText(cnamet);
                
                String cphonet=rs.getString("c_phone");
                cust_phone_txt.setText(cphonet);
               
              }
              rs.close();
              s.close();
              c.commit();
              c.close();
              
              //sum of resorses cost
              Class.forName("org.sqlite.JDBC");
              c = DriverManager.getConnection("jdbc:sqlite:decor.db");
              c.setAutoCommit(false);
              s=c.createStatement();
              String sql_proj_setails="select sum(price) as 'price' from details_res where p_serial="+pserialt+"";
              rs=s.executeQuery(sql_proj_setails);
              if(rs.next()){
               
                
                  String pricet=rs.getString("price");
                  sum_res_txt.setText(pricet);
              }
              rs.close();
              s.close();
              c.commit();
              c.close();
              //sum of customer payments
              Class.forName("org.sqlite.JDBC");
              c = DriverManager.getConnection("jdbc:sqlite:decor.db");
              c.setAutoCommit(false);
              s=c.createStatement();
              String pay_sum="select payment1+payment2+payment3+payment4+payment5+payment6+payment7+payment8+payment9+payment10 as 'payment' from cust_payed where p_serial="+pserialt+" ";
              rs=s.executeQuery(pay_sum);
              if(rs.next()){
                  String payed=rs.getString("payment");
                  sum_cust_txt.setText(payed);
              }
              rs.close();
              s.close();
              c.commit();
              c.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }
        finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
        
        }

    }//GEN-LAST:event_pserial_comboActionPerformed
public void combo_fill(){
        Connection c=null;
        Statement s=null;
        ResultSet rs=null;
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            String sql="select p_serial from project;";
            rs=s.executeQuery(sql);
            while(rs.next()){
                String pname =rs.getString("p_serial");
                pserial_combo.addItem(pname);
               
            }
             s.close();
              c.commit();
              c.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"برجاء التأكد من قاعده البيانات او اغلاق البرنامج وتشغيله");
        }
        finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        print_report();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void print_report(){
        String pserialt=pserial_combo.getSelectedItem().toString();
        String pnamet=proj_name_txt.getText();
        String cnamet=cust_name_txt.getText();
        String cphonet=cust_phone_txt.getText();
        String scustt=sum_cust_txt.getText();
        String srest=sum_res_txt.getText();
        Document doc=new Document();
        try{
            PdfWriter.getInstance(doc, new FileOutputStream("C:\\report\\cust_report\\cust_state\\report.pdf"));
           // BaseFont bf1=BaseFont.createFont("C:\\Windows\\Fonts\\simpbdo.ttf", BaseFont.WINANSI, true);
            doc.open();
            Image img=Image.getInstance("C:\\report\\all_emp\\ModernDesignlogo.jpg");
            //img.setAbsolutePosition(30f, 700f);
            doc.add(img);
            PdfPTable headtable=new PdfPTable(1);
            headtable.setRunDirection(PdfWriter.RUN_DIRECTION_RTL);
            PdfPCell headcell=new PdfPCell();
            headcell.setBorder(Rectangle.NO_BORDER);
            
      
            PdfPCell preport=new PdfPCell(new Paragraph("التقرير",Tahoma));
           // cnamec.setBackgroundColor(BaseColor.YELLOW);
            preport.setHorizontalAlignment(Element.ALIGN_CENTER);
            preport.setBorder(Rectangle.NO_BORDER);
            headtable.addCell(preport);
            
           
            doc.add(headtable);
            
           // doc.add(new Paragraph());
            doc.add(new Paragraph("\n"));

            PdfPTable bodytable=new PdfPTable(2);
            bodytable.setRunDirection(PdfWriter.RUN_DIRECTION_RTL);
            PdfPCell bodycell=new PdfPCell();
           bodycell.setBorder(Rectangle.NO_BORDER);
           
           PdfPCell pserialar=new PdfPCell(new Paragraph("رقم المشروع",Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            pserialar.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(pserialar);
            
            PdfPCell pserialv=new PdfPCell(new Paragraph(pserialt,Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            pserialv.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(pserialv);
            
            PdfPCell pnamear=new PdfPCell(new Paragraph("اسم المشروع",Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            pnamear.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(pnamear);
            
            PdfPCell pnamev=new PdfPCell(new Paragraph(pnamet,Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            pnamev.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(pnamev);
            
            PdfPCell cnamar=new PdfPCell(new Paragraph("اسم العميل",Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            cnamar.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(cnamar);
            
            PdfPCell cnamev=new PdfPCell(new Paragraph(cnamet,Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            cnamev.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(cnamev);
            
            PdfPCell cphonear=new PdfPCell(new Paragraph("رقم الهاتف",Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            cphonear.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(cphonear);
            
            PdfPCell cphonev=new PdfPCell(new Paragraph(cphonet,Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            cphonev.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(cphonev);
            
            PdfPCell cpayedar=new PdfPCell(new Paragraph("مجموع دفعات العميل",Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            cpayedar.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(cpayedar);
            
            PdfPCell sumv=new PdfPCell(new Paragraph(scustt,Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            sumv.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(sumv);
            
            PdfPCell restt=new PdfPCell(new Paragraph("تكلفة الخامات",Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            restt.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(restt);
            
            PdfPCell restv=new PdfPCell(new Paragraph(srest,Tahoma));
           // pserialar.setBackgroundColor(BaseColor.YELLOW);
            restv.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(restv);
            
            doc.add(bodytable);
            doc.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "برجاء اغلاق "
                    + "report.pdf");
        }
          if (Desktop.isDesktopSupported()) {
    try {
        File myFile = new File("C:\\report\\cust_report\\cust_state\\report.pdf");
        Desktop.getDesktop().open(myFile);
    }
    catch (IOException ex) {
        JOptionPane.showMessageDialog(null, "لايمكن فتح "
                + "report.pdf");}
         }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cust_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cust_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cust_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cust_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cust_report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cust_name_txt;
    private javax.swing.JLabel cust_phone_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel proj_name_txt;
    private javax.swing.JComboBox pserial_combo;
    private javax.swing.JLabel sum_cust_txt;
    private javax.swing.JLabel sum_res_txt;
    // End of variables declaration//GEN-END:variables
}
