/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package decoration;

import com.itextpdf.text.Document;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import static decoration.project_state.Tahoma;
import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author salah
 */
public class emp_project_state extends javax.swing.JFrame {

    /**
     * Creates new form emp_project_state
     */
    public emp_project_state() {
        initComponents();
        this.setLocationRelativeTo(null);
        state();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        emp_num_txt = new javax.swing.JLabel();
        emp_salary_txt = new javax.swing.JLabel();
        proj_num_txt = new javax.swing.JLabel();
        payed_cont_txt = new javax.swing.JLabel();
        price_txt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        payed_details_txt = new javax.swing.JLabel();
        payed_txt = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel1.setText("عدد الموظفين");

        jLabel2.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel2.setText("مرتبات الموظفين");

        jLabel3.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel3.setText("عدد المشاريع");

        jLabel4.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel4.setText("مجموع ماتم دفعه للمقاولين");

        jLabel5.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel5.setText("مجموع قيم الخامات");

        emp_num_txt.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N

        emp_salary_txt.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N

        proj_num_txt.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N

        payed_cont_txt.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N

        price_txt.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel6.setText("مجموع ماتم دفعه للخامات");

        jLabel7.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel7.setText("مجموع ماتم دفعه");

        payed_details_txt.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N

        payed_txt.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(payed_details_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(76, 76, 76))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emp_num_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(emp_salary_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(proj_num_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(payed_cont_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(price_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(payed_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))))
                .addGap(134, 134, 134))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(emp_num_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(emp_salary_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(proj_num_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(payed_cont_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(payed_details_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(payed_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(price_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\close.png")); // NOI18N
        jMenuItem1.setText("إغلاق");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("التقرير");
        jMenu2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\printer.png")); // NOI18N
        jMenuItem3.setText("طباعه التقرير");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
                Document doc=new Document();
                String emp_num = emp_num_txt.getText();
                String emp_salary = emp_salary_txt.getText();
                String proj_num = proj_num_txt.getText();
                String payed_cont = payed_cont_txt.getText();
                String payed_details = payed_details_txt.getText();
                String payed = payed_txt.getText();
                String rest=price_txt.getText();

         try{
            PdfWriter.getInstance(doc, new FileOutputStream("C:\\report\\all_report\\report.pdf"));
           // BaseFont bf1=BaseFont.createFont("C:\\Windows\\Fonts\\simpbdo.ttf", BaseFont.WINANSI, true);
            doc.open();
            Image img=Image.getInstance("C:\\report\\all_emp\\ModernDesignlogo.jpg");
            //img.setAbsolutePosition(30f, 700f);
            doc.add(img);
            PdfPTable headtable=new PdfPTable(1);
            headtable.setRunDirection(PdfWriter.RUN_DIRECTION_RTL);
            PdfPCell headcell=new PdfPCell();
            headcell.setBorder(Rectangle.NO_BORDER);
            Paragraph preport;
            preport= new Paragraph("التقرير\n" ,Tahoma);
            preport.setAlignment(PdfPCell.ALIGN_LEFT);
            headcell.addElement(preport);
            headtable.addCell(headcell);
            doc.add(headtable);
            
          
           // doc.add(new Paragraph());
            doc.add(new Paragraph("\n"));

            PdfPTable bodytable=new PdfPTable(2);
            bodytable.setRunDirection(PdfWriter.RUN_DIRECTION_RTL);
            PdfPCell bodycell=new PdfPCell();
           bodycell.setBorder(Rectangle.NO_BORDER);
           
            Paragraph enumar;
            enumar= new Paragraph("عدد الموظفين" ,Tahoma);
            enumar.setAlignment(PdfPCell.ALIGN_RIGHT);
           // bodycell.addElement(pserialar);
            bodytable.addCell(enumar);
            
            Paragraph enumv;
            enumv= new Paragraph(emp_num ,Tahoma);
            enumv.setAlignment(PdfPCell.ALIGN_RIGHT);
           // bodycell.addElement(pserialv);
                        bodytable.addCell(enumv);
                        
            Paragraph esalaryar;
            esalaryar= new Paragraph("مجموع مرتبات الموظفين" ,Tahoma);
            esalaryar.setAlignment(PdfPCell.ALIGN_RIGHT);
           // bodycell.addElement(pserialar);
            bodytable.addCell(esalaryar);
            
            Paragraph esalaryv;
            esalaryv= new Paragraph(emp_salary ,Tahoma);
            esalaryv.setAlignment(PdfPCell.ALIGN_RIGHT);
           // bodycell.addElement(pserialv);
                        bodytable.addCell(esalaryv);

            
            Paragraph projnumar;
            projnumar= new Paragraph("عدد المشاريع" ,Tahoma);
            projnumar.setAlignment(PdfPCell.ALIGN_RIGHT);
           // bodycell.addElement(pserialar);
            bodytable.addCell(projnumar);
            
            Paragraph projnumv;
            projnumv= new Paragraph(proj_num ,Tahoma);
            projnumv.setAlignment(PdfPCell.ALIGN_RIGHT);
           // bodycell.addElement(pserialv);
                        bodytable.addCell(projnumv);
            
                        
            Paragraph pcontar;
            pcontar= new Paragraph("مجموع ماتم دفعه للمقاولين" ,Tahoma);
            pcontar.setAlignment(PdfPCell.ALIGN_RIGHT);
           // bodycell.addElement(pserialar);
            bodytable.addCell(pcontar);
            
            Paragraph pcontv;
            pcontv= new Paragraph(payed_cont ,Tahoma);
            pcontv.setAlignment(PdfPCell.ALIGN_RIGHT);
           // bodycell.addElement(pserialv);
                        bodytable.addCell(pcontv);
                        
                        
             Paragraph pdetailsar;
            pdetailsar= new Paragraph("مجموع ماتم دفعه للخامات" ,Tahoma);
            pdetailsar.setAlignment(PdfPCell.ALIGN_RIGHT);
           // bodycell.addElement(pserialar);
            bodytable.addCell(pdetailsar);
            
            Paragraph pdetailsv;
            pdetailsv= new Paragraph(payed_details ,Tahoma);
            pdetailsv.setAlignment(PdfPCell.ALIGN_RIGHT);
           // bodycell.addElement(pserialv);
            bodytable.addCell(pdetailsv);
                        
            Paragraph payedar;
            payedar= new Paragraph("مجموع ماتم دفعه" ,Tahoma);
            payedar.setAlignment(PdfPCell.ALIGN_RIGHT);
           // bodycell.addElement(pserialar);
            bodytable.addCell(payedar);
            
            Paragraph payedv;
            payedv= new Paragraph(payed ,Tahoma);
            payedv.setAlignment(PdfPCell.ALIGN_RIGHT);
           // bodycell.addElement(pserialv);
            bodytable.addCell(payedv);
                        
            Paragraph restar;
            restar= new Paragraph("مجموع المتبقى للخامات" ,Tahoma);
            restar.setAlignment(PdfPCell.ALIGN_RIGHT);
           // bodycell.addElement(pserialar);
            bodytable.addCell(restar);
            
            Paragraph restv;
            restv= new Paragraph(rest ,Tahoma);
            restv.setAlignment(PdfPCell.ALIGN_RIGHT);
           // bodycell.addElement(pserialv);
                        bodytable.addCell(restv);
                        
            //bodytable.addCell(bodycell);
            doc.add(bodytable);
            doc.close();
        }catch(Exception e){JOptionPane.showMessageDialog(null, "لايمكن كتابه التقرير برجاء اغلاق "
                + "report.pdf");}
         
          if (Desktop.isDesktopSupported()) {
    try {
        File myFile = new File("C:\\report\\all_report\\report.pdf");
        Desktop.getDesktop().open(myFile);
    }
    catch (IOException ex) {
        JOptionPane.showMessageDialog(null, "لايمكن فتح"
                + "report.pdf");}
         }
//        
        
    
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    //get statics from all tables
    public void state(){
        Connection c= null;
        Statement s=null;
        ResultSet rs=null;
        try{
            //number of employee
            Class.forName("org.sqlite.JDBC");
              c = DriverManager.getConnection("jdbc:sqlite:decor.db");
              c.setAutoCommit(false);
              s=c.createStatement();
              String sql="select count(e_serial) as 'emp_num' from emp";
              rs=s.executeQuery(sql);
              if(rs.next()){
                String empnumt=rs.getString("emp_num");
                emp_num_txt.setText(empnumt);
               
              }
              rs.close();
              s.close();
              c.commit();
              c.close();
              
              //employee's salary sum
              Class.forName("org.sqlite.JDBC");
              c = DriverManager.getConnection("jdbc:sqlite:decor.db");
              c.setAutoCommit(false);
              s=c.createStatement();
              String sql_sal="select sum(e_salary) as 'e_salary' from emp";
              rs=s.executeQuery(sql_sal);
              if(rs.next()){
                String salaryt=rs.getString("e_salary");
                emp_salary_txt.setText(salaryt);
               
              }
              rs.close();
              s.close();
              c.commit();
              c.close();
              //projects number
              Class.forName("org.sqlite.JDBC");
              c = DriverManager.getConnection("jdbc:sqlite:decor.db");
              c.setAutoCommit(false);
              s=c.createStatement();
              String sql_proj_num="select count(p_serial) as 'p_serial' from project";
              rs=s.executeQuery(sql_proj_num);
              if(rs.next()){
                String pserialt=rs.getString("p_serial");
                proj_num_txt.setText(pserialt);
               
              }
              rs.close();
              s.close();
              c.commit();
              c.close();
              //payed fro contractor
              Class.forName("org.sqlite.JDBC");
              c = DriverManager.getConnection("jdbc:sqlite:decor.db");
              c.setAutoCommit(false);
              s=c.createStatement();
              String sql_proj_payed="select sum(payment1)+sum(payment2)+sum(payment3)+sum(payment4)+sum(payment5)+sum(payment6)+sum(payment7)+sum(payment8)+sum(payment9)+sum(payment10) as 'payment' from proj_contractor";
              rs=s.executeQuery(sql_proj_payed);
              if(rs.next()){
                String paymentt=rs.getString("payment");
                payed_cont_txt.setText(paymentt);
               
              }
              rs.close();
              s.close();
              c.commit();
              c.close();
              
              //payed for materials
              Class.forName("org.sqlite.JDBC");
              c = DriverManager.getConnection("jdbc:sqlite:decor.db");
              c.setAutoCommit(false);
              s=c.createStatement();
              String sql_proj_m="select sum(payed) as 'payed' from details_res";
              rs=s.executeQuery(sql_proj_m);
              if(rs.next()){
                String payedt=rs.getString("payed");
                payed_details_txt.setText(payedt);
               
              }
              rs.close();
              s.close();
              c.commit();
              c.close();
              
              //sum of payment 
              double payedtt=Double.parseDouble(payed_details_txt.getText());
              double cpayedtt=Double.parseDouble(payed_cont_txt.getText());
              double p=payedtt+cpayedtt;
              payed_txt.setText(Double.toString(p));
              // rest sum
              Class.forName("org.sqlite.JDBC");
              c = DriverManager.getConnection("jdbc:sqlite:decor.db");
              c.setAutoCommit(false);
              s=c.createStatement();
              String sql_proj_r="select sum(price) as 'price' from details_res";
              rs=s.executeQuery(sql_proj_r);
              if(rs.next()){
                String restt=rs.getString("price");
                price_txt.setText(restt);
               
              }
              rs.close();
              s.close();
              c.commit();
              c.close();
              
              
        }catch(Exception e){JOptionPane.showMessageDialog(null, "برجاء المحاوله مره اخرى او اغلاق البرنامج وتشغيله");}
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public void close(){
        

        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEve­ntQueue().postEvent(winClosingEvent);
     }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emp_project_state.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emp_project_state.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emp_project_state.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emp_project_state.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emp_project_state().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emp_num_txt;
    private javax.swing.JLabel emp_salary_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel payed_cont_txt;
    private javax.swing.JLabel payed_details_txt;
    private javax.swing.JLabel payed_txt;
    private javax.swing.JLabel price_txt;
    private javax.swing.JLabel proj_num_txt;
    // End of variables declaration//GEN-END:variables
}
