/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package decoration;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import static decoration.project_state.fontSize;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.*;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author salah
 */
public class project_contractor extends javax.swing.JFrame {

    /**
     * Creates new form all_project
     */
    public project_contractor() {
        initComponents();
//        this.setLocationRelativeTo(null);
       // show_details();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        combo_fill();

        
    }
        public static Font Tahoma = FontFactory.getFont("c://windows//fonts//tahoma.ttf",
                            BaseFont.IDENTITY_H,fontSize);

    public void close(){
        

        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEve­ntQueue().postEvent(winClosingEvent);
        
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        contractor_compo = new javax.swing.JComboBox();
        hours_txt = new javax.swing.JTextField();
        p_serial_txt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        del_details = new javax.swing.JButton();
        new_details = new javax.swing.JButton();
        cont_name_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        payment5_txt = new javax.swing.JTextField();
        payment3_txt = new javax.swing.JTextField();
        payment1_txt = new javax.swing.JTextField();
        payment2_txt = new javax.swing.JTextField();
        payment4_txt = new javax.swing.JTextField();
        payment6_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        payment7_txt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        payment9_txt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        payment8_txt = new javax.swing.JTextField();
        payment10_txt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        date1 = new javax.swing.JTextField();
        date2 = new javax.swing.JTextField();
        date3 = new javax.swing.JTextField();
        date4 = new javax.swing.JTextField();
        date5 = new javax.swing.JTextField();
        date6 = new javax.swing.JTextField();
        date7 = new javax.swing.JTextField();
        date8 = new javax.swing.JTextField();
        date9 = new javax.swing.JTextField();
        date10 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        cont_phone_txt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        sum_txt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        proj_name = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        custphone_txt = new javax.swing.JLabel();
        eserial_txt = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cust_name = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ename_txt = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pserial_txt = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        sum_tbl = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        all_proj_jtable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel8.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("المقاولون");

        contractor_compo.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N

        hours_txt.setText("0.0");

        p_serial_txt.setBackground(new java.awt.Color(102, 255, 102));
        p_serial_txt.setText("...");

        jLabel3.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("عدد الساعات");

        jButton1.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 0));
        jButton1.setText("حفظ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        del_details.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        del_details.setForeground(new java.awt.Color(0, 153, 0));
        del_details.setText("حذف");
        del_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_detailsActionPerformed(evt);
            }
        });

        new_details.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        new_details.setForeground(new java.awt.Color(0, 153, 0));
        new_details.setText("جديد");
        new_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_detailsActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("اسم المقاول");

        jLabel2.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("الدفعات 1");

        payment5_txt.setText("0.0");

        payment3_txt.setText("0.0");

        payment1_txt.setText("0.0");
        payment1_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment1_txtActionPerformed(evt);
            }
        });

        payment2_txt.setText("0.0");

        payment4_txt.setText("0.0");

        payment6_txt.setText("0.0");

        jLabel5.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("الدفعات 4");

        jLabel14.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("الدفعات 6");

        jLabel15.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 255));
        jLabel15.setText("الدفعات 2");

        jLabel16.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 255));
        jLabel16.setText("الدفعات 3");

        jLabel17.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 255));
        jLabel17.setText("الدفعات 5");

        payment7_txt.setText("0.0");

        jLabel18.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 255));
        jLabel18.setText("الدفعات 7");

        payment9_txt.setText("0.0");

        jLabel19.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 255));
        jLabel19.setText("الدفعات 9");

        jLabel20.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 255));
        jLabel20.setText("الدفعات 8");

        payment8_txt.setText("0.0");

        payment10_txt.setText("0.0");

        jLabel21.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 255));
        jLabel21.setText("الدفعات 10");

        jLabel22.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 255));
        jLabel22.setText("رقم المشروع");

        jLabel1.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("التاريخ");

        jLabel4.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("التاريخ");

        jLabel23.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 255));
        jLabel23.setText("التاريخ");

        jLabel24.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 255));
        jLabel24.setText("التاريخ");

        jLabel25.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 255));
        jLabel25.setText("التاريخ");

        jLabel26.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 255));
        jLabel26.setText("التاريخ");

        jLabel27.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 255));
        jLabel27.setText("التاريخ");

        jLabel28.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 255));
        jLabel28.setText("التاريخ");

        jLabel29.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 255));
        jLabel29.setText("التاريخ");

        jLabel30.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 255));
        jLabel30.setText("التاريخ");

        jLabel31.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 255));
        jLabel31.setText("رقم التليفون");

        jButton3.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 0));
        jButton3.setText("طباعه");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 255));
        jLabel32.setText("مجموع الدفعات");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel22)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(p_serial_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel30))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(hours_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(date4, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(date7, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(date10, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(50, 50, 50)))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel17)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel20))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(new_details, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(57, 57, 57)
                                                .addComponent(del_details, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(payment2_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                                        .addComponent(payment5_txt))
                                                    .addComponent(payment8_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(71, 71, 71)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                                    .addComponent(jLabel28))
                                                .addGap(34, 34, 34)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(date2)
                                                    .addComponent(date5)
                                                    .addComponent(date8, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel16)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(payment3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel23)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(date3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel14)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(payment6_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(date6))
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel19)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(payment9_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel29)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(date9))
                                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jLabel32)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(sum_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(cont_name_txt, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(contractor_compo, javax.swing.GroupLayout.Alignment.LEADING, 0, 220, Short.MAX_VALUE))
                                                .addGap(45, 45, 45)
                                                .addComponent(jLabel31)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cont_phone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(payment7_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(payment1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(payment4_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(54, 54, 54))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(payment10_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cont_phone_txt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(p_serial_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)
                        .addComponent(jLabel3)
                        .addComponent(hours_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(cont_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31)))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(payment1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(payment2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(payment3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23)
                        .addComponent(date3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(payment4_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)
                        .addComponent(date4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(payment5_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel25)
                        .addComponent(jLabel14)
                        .addComponent(payment6_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26)
                        .addComponent(date6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(payment7_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(date7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(payment8_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(date8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(payment9_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(date9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(payment10_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(date10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(contractor_compo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(sum_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(del_details, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new_details, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "المشروع", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 11))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("تليفون العميل");

        jLabel9.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("اسم العميل");

        jLabel12.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("اسم الموظف المسئول");

        jLabel11.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("رقم الموظف");

        jLabel7.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("اسم المشروع");

        jLabel13.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("رقم المشروع");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(46, 46, 46)
                .addComponent(pserial_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(proj_name, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(cust_name, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(custphone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(27, 27, 27)
                .addComponent(eserial_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(ename_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(proj_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cust_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custphone_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(eserial_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pserial_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(ename_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jButton2.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jButton2.setText("عرض البيانات");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        sum_tbl.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        sum_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(sum_tbl);

        all_proj_jtable.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        all_proj_jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        all_proj_jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                all_proj_jtableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(all_proj_jtable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(304, 304, 304))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1389, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(296, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jMenu1.setText("File");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("طباعه");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("اغلاق");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("الخروج من البرنامج");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        insert_db();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void del_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_detailsActionPerformed
        // TODO add your handling code here:
        del_details();
    }//GEN-LAST:event_del_detailsActionPerformed

    private void new_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_detailsActionPerformed
        // TODO add your handling code here:
        new_details();
    }//GEN-LAST:event_new_detailsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
show_details();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void payment1_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment1_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payment1_txtActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         MessageFormat header=new MessageFormat("Report print");
        MessageFormat footer=new MessageFormat("page{0, number,integer}");
        try{
            all_proj_jtable.print(JTable.PrintMode.FIT_WIDTH,header,footer);
             
              
              
        }catch(Exception e){JOptionPane.showMessageDialog(null,"لايمكن الطباعه برجاء المحاوله لاحقا");}
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void all_proj_jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_all_proj_jtableMouseClicked
        // TODO add your handling code here:
        getting_data();
    }//GEN-LAST:event_all_proj_jtableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        print_details();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
     public void combo_fill(){
        Connection c=null;
        Statement s=null;
        ResultSet rs=null;
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            String sql="select cont from cont_combo;";
            rs=s.executeQuery(sql);
            while(rs.next()){
                String pname =rs.getString("cont");
                contractor_compo.addItem(pname);
               
            }
             s.close();
              c.commit();
              c.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"برجاء التاكد من قاعده البيانات او اغلاق وتشغيل البرنامج");
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }
    //this fu selects all employee data from DB
    public void show_details(){
        Connection c=null;
        Statement s=null;
      // all_project ap=new all_project();
       String pserialt=pserial_txt.getText();
     //  jLabel5.setText(pserialt);
        
        try{
              Class.forName("org.sqlite.JDBC");
              c = DriverManager.getConnection("jdbc:sqlite:decor.db");
              c.setAutoCommit(false);
              s=c.createStatement();
              String sql="select p_serial as 'رقم المشروع', hours as 'عدد الساعات', cont_name as 'اسم المقاول', tag as 'المقاولون',payment1 as 'الدفعات 1',payment2 as 'الدفعات 2',payment3 as 'الدفعات 3',payment4 as 'الدفعات 4',payment5 as 'الدفعات 5',payment6 as 'الدفعات 6',payment7 as 'الدفعات 7',payment8 as 'الدفعات 8',payment9 as 'الدفعات 9',payment10 as 'الدفعات 10',payment1+payment2+payment3+payment4+payment5+payment6+payment7+payment8+payment9+payment10 as 'مجموع الدفعات' "
                      + "from proj_contractor"
                      + " where p_serial = "+pserialt+"";
              all_proj_jtable.setModel(DbUtils.resultSetToTableModel(s.executeQuery(sql)));
              s.close();
              c.commit();
              c.close();
              sum(); // sum of payed and rest column
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"لايمكن اجراء العمليه برجاء التاكد من قاعده البيانات");
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }
    
    //getting data from jtable to jtext field and jlabel
    public void getting_data(){
        //connecting to DB
        Connection c= null;
        PreparedStatement pst=null;
        ResultSet rs=null;
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            int row=all_proj_jtable.getSelectedRow();
            String serial=(all_proj_jtable.getModel().getValueAt(row, 0).toString());
            String tag=(all_proj_jtable.getModel().getValueAt(row, 3).toString());
            String sql="select * from proj_contractor where p_serial="+serial+" and tag ='"+tag+"'";
            pst=(PreparedStatement) c.prepareStatement(sql);
            rs=pst.executeQuery(); 
            if(rs.next()){
                String serialt=rs.getString("p_serial");
                p_serial_txt.setText(serialt);
                
                String hourt=rs.getString("hours");
                hours_txt.setText(hourt);
                
                
                String cont_namet=rs.getString("cont_name");
                cont_name_txt.setText(cont_namet);
                
                String phone_numt=rs.getString("cont_phone");
                cont_phone_txt.setText(phone_numt);
                
                 String tagt=rs.getString("tag");
                 contractor_compo.setSelectedItem(tagt); 
                 
                String payment1=rs.getString("payment1");
                payment1_txt.setText(payment1);
                  String payment2=rs.getString("payment2");
                payment2_txt.setText(payment2);
                  String payment3=rs.getString("payment3");
                payment3_txt.setText(payment3);
                  String payment4=rs.getString("payment4");
                payment4_txt.setText(payment4);
                  String payment5=rs.getString("payment5");
                payment5_txt.setText(payment5);
                  String payment6=rs.getString("payment6");
                payment6_txt.setText(payment6);
                  String payment7=rs.getString("payment7");
                payment7_txt.setText(payment7);
                  String payment8=rs.getString("payment8");
                payment8_txt.setText(payment8);
                  String payment9=rs.getString("payment9");
                payment9_txt.setText(payment9);
                  String payment10=rs.getString("payment10");
                payment10_txt.setText(payment10);
                
            }
            //selecting date into jtextfield
            String sql_select_date="select * from cont_date where p_serial="+serial+" and tag ='"+tag+"' ";
            pst=(PreparedStatement) c.prepareStatement(sql_select_date);
            rs=pst.executeQuery();
            if(rs.next()){
                String date1t=rs.getString("date1");
                date1.setText(date1t);
                
                String date2t=rs.getString("date2");
                date2.setText(date2t);
                
                String date3t=rs.getString("date3");
                date3.setText(date3t);
                
                String date4t=rs.getString("date4");
                date4.setText(date4t);
                
                String date5t=rs.getString("date5");
                date5.setText(date5t);
                
                String date6t=rs.getString("date6");
                date6.setText(date6t);
                
                String date7t=rs.getString("date7");
                date7.setText(date7t);
                
                String date8t=rs.getString("date8");
                date8.setText(date8t);
                
                String date9t=rs.getString("date9");
                date9.setText(date9t);
                
                String date10t=rs.getString("date10");
                date10.setText(date10t);
               // JOptionPane.showMessageDialog(null, "done");
            }
            
            String sum_sql="select payment1+payment2+payment3+payment4+payment5+payment6+payment7+payment8+payment9+payment10 as 'sum' from proj_contractor where p_serial="+serial+" and tag ='"+tag+"' ";
            pst=(PreparedStatement) c.prepareStatement(sum_sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String sumt=rs.getString("sum");
                sum_txt.setText(sumt);
            
                
            }
            rs.close();
              pst.close();
              c.commit();
              c.close();
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"لايمكن اجراء العمليه برجاء المحاوله مره اخرى");
        }
         finally{
            try{
               
          //  rs.close();
            pst.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }
    
    
    //insert employee id to database
    public void insert_db(){
        Connection c=null;
        Statement s=null;
        ResultSet rs=null;
        String payment1=payment1_txt.getText();
        String payment2=payment2_txt.getText();
        String payment3=payment3_txt.getText();
        String payment4=payment4_txt.getText();
        String payment5=payment5_txt.getText();
        String payment6=payment6_txt.getText();
        String payment7=payment7_txt.getText();
        String payment8=payment8_txt.getText();
        String payment9=payment9_txt.getText();
        String payment10=payment10_txt.getText();
        
        String date1t=date1.getText();
        String date2t=date2.getText();
        String date3t=date3.getText();
        String date4t=date4.getText();
        String date5t=date5.getText();
        String date6t=date6.getText();
        String date7t=date7.getText();
        String date8t=date8.getText();
        String date9t=date9.getText();
        String date10t=date10.getText();

        String hourt=hours_txt.getText();
        String cont_namet=cont_name_txt.getText();
        String cont_phonet=cont_phone_txt.getText();
        String tagt=contractor_compo.getSelectedItem().toString();
        String pserial=null;
        String st=p_serial_txt.getText();
        String proj_namet=proj_name.getText();
        
        
        try{
            
            //insert new
            if(st=="..."){
                pserial=pserial_txt.getText();
            
            
                Class.forName("org.sqlite.JDBC");
                c = DriverManager.getConnection("jdbc:sqlite:decor.db");
                c.setAutoCommit(false);
                s=c.createStatement();
                String sql2="select * from proj_contractor where p_serial="+pserial+" and tag='"+tagt+"' ";
                rs=s.executeQuery(sql2);
            
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "لقد قمت بتسجيل هذا المقاول مسبقا");
                       rs.close();

            //show_details();   
            }
            
            else{
                 
                
            String sql="insert into proj_contractor(p_serial,hours,cont_name,cont_phone,tag,payment1,payment2,payment3,payment4,payment5,payment6,payment7,payment8,payment9,payment10)"+
                               " values("+pserial+","+hourt+",'"+cont_namet+"','"+cont_phonet+"','"+tagt+"',"+payment1+","+payment2+","+payment3+","+payment4+","+payment5+","+payment6+","+payment7+","+payment8+","+payment9+","+payment10+");";
            s.executeUpdate(sql);
            
            String sql_insert_date="insert into cont_date(p_serial,date1,date2,date3,date4,date5,date6,date7,date8,date9,date10,tag) "
                    + "values("+pserial+",'"+date1t+"','"+date2t+"','"+date3t+"','"+date4t+"','"+date5t+"','"+date6t+"','"+date7t+"','"+date8t+"','"+date9t+"','"+date10t+"','"+tagt+"')";
            s.executeUpdate(sql_insert_date);

           // show_details();
            }
            String sum_sql="select payment1+payment2+payment3+payment4+payment5+payment6+payment7+payment8+payment9+payment10 as 'sum' from proj_contractor where p_serial="+pserial+" and tag ='"+tagt+"' ";
            
            rs=s.executeQuery(sum_sql);
            if(rs.next()){
                String sumt=rs.getString("sum");
                sum_txt.setText(sumt);
            
                
            }
            
            s.close();
            c.commit();
            c.close();
           show_details();
             
            }else{
                                //update existing client

                Class.forName("org.sqlite.JDBC");
                c = DriverManager.getConnection("jdbc:sqlite:decor.db");
                c.setAutoCommit(false);
                s=c.createStatement();
                String sql_update="update proj_contractor "
                        + "set hours="+hourt+",cont_name='"+cont_namet+"',cont_phone='"+cont_phonet+"',payment1="+payment1+",payment2="+payment2+",payment3="+payment3+",payment4="+payment4+",payment5="+payment5+",payment6="+payment6+",payment7="+payment7+",payment8="+payment8+",payment9="+payment9+",payment10="+payment10+""
                        + " where p_serial="+st+" and tag='"+tagt+"';";
                s.executeUpdate(sql_update);
                
                String date_update="update cont_date "
                        + "set date1='"+date1t+"',date2='"+date2t+"', date3='"+date3t+"',date4='"+date4t+"',date5='"+date5t+"',date6='"+date6t+"',date7='"+date7t+"',date8='"+date8t+"',date9='"+date9t+"',date10='"+date10t+"'  "
                        + "where p_serial="+st+" and tag='"+tagt+"' ";
                s.executeUpdate(date_update);
                 String sum_sql="select payment1+payment2+payment3+payment4+payment5+payment6+payment7+payment8+payment9+payment10 as 'sum' from proj_contractor where p_serial="+st+" and tag ='"+tagt+"' ";
            
            rs=s.executeQuery(sum_sql);
            if(rs.next()){
                String sumt=rs.getString("sum");
                sum_txt.setText(sumt);
            
                
            }
            s.close();
            c.commit();
            c.close();
            show_details();
            
            }
                       
            
           // s.close();
        }catch(Exception e){
          //  JOptionPane.showMessageDialog(null, e);
            JOptionPane.showMessageDialog(null,"خطأ برجاء المحاوله مره اخرى او اغلاق البرنامج وتشغيله");
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }
    
    //empty jtext fields to insert new details
    public void new_details(){
        try{
            p_serial_txt.setText("...");
            hours_txt.setText("0.0");
            payment1_txt.setText("0.0");
            payment2_txt.setText("0.0");
            payment3_txt.setText("0.0");
            payment4_txt.setText("0.0");
            payment5_txt.setText("0.0");
            payment6_txt.setText("0.0");
            payment7_txt.setText("0.0");
            payment8_txt.setText("0.0");
            payment9_txt.setText("0.0");
            payment10_txt.setText("0.0");
            cont_name_txt.setText(null);
            cont_phone_txt.setText(null);
            sum_txt.setText(null);
            
            date1.setText(null);
            date2.setText(null);
            date3.setText(null);
            date4.setText(null);
            date5.setText(null);
            date6.setText(null);
            date7.setText(null);
            date8.setText(null);
            date9.setText(null);
            date10.setText(null);

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"برجاء المحاوله مره اخرى");
        }
        
    }
    //delete project details
    public void del_details(){
        Connection c= null;
        Statement s=null;
        String pserialt=p_serial_txt.getText();
        String tagt=contractor_compo.getSelectedItem().toString();
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            String sql_del="delete from proj_contractor where p_serial="+pserialt+" and tag='"+tagt+"';";
            s.executeUpdate(sql_del);
            String date_del="delete from cont_date where p_serial="+pserialt+" and tag='"+tagt+"' ";
            s.executeUpdate(date_del);
            s.close();
            c.commit();
            c.close();
            show_details();
            new_details();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"لا يمكن الحزف برجاء المحاوله مره اخرى ");
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }
    
    //sum for payed coulmn and rest column
    public void sum(){
        Connection c = null;
        Statement s = null;
        ResultSet rs = null;
        try{
            String serialt=pserial_txt.getText();
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            String sql_payed = "select sum(payment1)+sum(payment2)+sum(payment3)+sum(payment4)+sum(payment5)+sum(payment6)+sum(payment7)+sum(payment8)+sum(payment9)+sum(payment10) as 'مجموع ماتم دفعه' from proj_contractor where p_serial="+serialt+"";
            rs=s.executeQuery(sql_payed);
            sum_tbl.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            s.close();
            c.commit();
            c.close();
            
           
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"لايمكن جمع الدفعات");
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    
    }
         
    
       
    
    public void print_details(){
        getting_data();
        String payment1=payment1_txt.getText();
        String payment2=payment2_txt.getText();
        String payment3=payment3_txt.getText();
        String payment4=payment4_txt.getText();
        String payment5=payment5_txt.getText();
        String payment6=payment6_txt.getText();
        String payment7=payment7_txt.getText();
        String payment8=payment8_txt.getText();
        String payment9=payment9_txt.getText();
        String payment10=payment10_txt.getText();
        
        String date1t=date1.getText();
        String date2t=date2.getText();
        String date3t=date3.getText();
        String date4t=date4.getText();
        String date5t=date5.getText();
        String date6t=date6.getText();
        String date7t=date7.getText();
        String date8t=date8.getText();
        String date9t=date9.getText();
        String date10t=date10.getText();

        String hourt=hours_txt.getText();
        String sumt=sum_txt.getText();
        String cont_namet=cont_name_txt.getText();
        String cont_phonet=cont_phone_txt.getText();
        String tagt=contractor_compo.getSelectedItem().toString();
        String pserial=null;
        String st=p_serial_txt.getText();
        String proj_namet=proj_name.getText();
        Document doc=new Document();
        try{
            PdfWriter.getInstance(doc, new FileOutputStream("C:\\report\\cont_report\\report.pdf"));
            doc.open();
            Image img=Image.getInstance("C:\\report\\all_emp\\ModernDesignlogo.jpg");
            //img.setAbsolutePosition(30f, 700f);
            doc.add(img);
            PdfPTable headtable=new PdfPTable(1);
            headtable.setRunDirection(PdfWriter.RUN_DIRECTION_RTL);
           
            
            PdfPCell cellpayedn=new PdfPCell(new Paragraph("دفعات المقاول",Tahoma));
            cellpayedn.setBorder(Rectangle.NO_BORDER);
            cellpayedn.setHorizontalAlignment(Element.ALIGN_CENTER);
            headtable.addCell(cellpayedn);
            
           
            doc.add(headtable);
            doc.add(new Paragraph("\n"));

           // doc.add(new Paragraph("------------------------------------------------------------------------------------------------------------------------------"));
            
            PdfPTable dettbl=new PdfPTable(4);
            dettbl.setRunDirection(PdfWriter.RUN_DIRECTION_RTL);
            PdfPCell detcell=new PdfPCell();
            detcell.setBorder(Rectangle.NO_BORDER);
            
            
            PdfPCell cont_namear=new PdfPCell(new Paragraph("اسم المقاول",Tahoma));
            cont_namear.setBorder(Rectangle.NO_BORDER);
            cont_namear.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(cont_namear);
            
            PdfPCell cont_namev=new PdfPCell(new Paragraph(cont_namet,Tahoma));
            cont_namev.setBorder(Rectangle.NO_BORDER);
            cont_namev.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(cont_namev);
            
           PdfPCell cphonear=new PdfPCell(new Paragraph("التليفون",Tahoma));
            cphonear.setBorder(Rectangle.NO_BORDER);
            cphonear.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(cphonear);
            
            
            PdfPCell cphonev=new PdfPCell(new Paragraph("cont_phonet",Tahoma));
            cphonev.setBorder(Rectangle.NO_BORDER);
            cphonev.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(cphonev);
            
            doc.add(dettbl);
            
            //doc.add(new Paragraph("\n"));

            PdfPTable bodytable=new PdfPTable(3);
            bodytable.setRunDirection(PdfWriter.RUN_DIRECTION_RTL);
            PdfPCell bodycell=new PdfPCell();
           bodycell.setBorder(Rectangle.ALIGN_CENTER);
           
           bodytable.setWidths(new int[]{2,2,1});
          
             PdfPCell numar=new PdfPCell(new Paragraph("الرقم",Tahoma));
            numar.setBackgroundColor(BaseColor.YELLOW);
            numar.setHorizontalAlignment(Element.ALIGN_CENTER);
            //numar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(numar);
            
            
            PdfPCell paymentar=new PdfPCell(new Paragraph("الدفعات",Tahoma));
            paymentar.setBackgroundColor(BaseColor.YELLOW);
            paymentar.setHorizontalAlignment(Element.ALIGN_CENTER);
            //paymentar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(paymentar);
            
           
            PdfPCell datear=new PdfPCell(new Paragraph("التاريخ",Tahoma));
            datear.setBackgroundColor(BaseColor.YELLOW);
            datear.setHorizontalAlignment(Element.ALIGN_CENTER);
           // datear.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(datear);
           
            
            
            PdfPCell num1ar=new PdfPCell(new Paragraph("1",Tahoma));
            num1ar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  num1ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(num1ar);
            
            
            PdfPCell payment1ar=new PdfPCell(new Paragraph(payment1,Tahoma));
            payment1ar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  payment1ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(payment1ar);
            
            
            PdfPCell date1ar=new PdfPCell(new Paragraph(date1t,Tahoma));
            date1ar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  date1ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(date1ar);
            
           
            PdfPCell num2ar=new PdfPCell(new Paragraph("2",Tahoma));
            num2ar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  num2ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(num2ar);
            
            
            PdfPCell payment2ar=new PdfPCell(new Paragraph(payment2,Tahoma));
            payment2ar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  payment2ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(payment2ar);
            
           
            PdfPCell date2ar=new PdfPCell(new Paragraph(date2t,Tahoma));
            date2ar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  date2ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(date2ar);
            
           
            PdfPCell num3ar=new PdfPCell(new Paragraph("3",Tahoma));
            num3ar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  num3ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(num3ar);
            
           
             PdfPCell payment3ar=new PdfPCell(new Paragraph(payment3,Tahoma));
            payment3ar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  payment3ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(payment3ar);
            
            
            PdfPCell date3ar=new PdfPCell(new Paragraph(date3t,Tahoma));
            date3ar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  date3ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(date3ar);
            
            
            PdfPCell num4ar=new PdfPCell(new Paragraph("4",Tahoma));
            num4ar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  num4ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(num4ar);
            
           
             PdfPCell payment4ar=new PdfPCell(new Paragraph(payment4,Tahoma));
            payment4ar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  payment4ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(payment4ar);
            
         
             PdfPCell date4ar=new PdfPCell(new Paragraph(date4t,Tahoma));
            date4ar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  date4ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(date4ar);
            
            
            PdfPCell num5ar=new PdfPCell(new Paragraph("5",Tahoma));
            num5ar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  num5ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(num5ar);
            
            
            PdfPCell payment5ar=new PdfPCell(new Paragraph(payment5,Tahoma));
            payment5ar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  payment5ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(payment5ar);
            
            
            PdfPCell date5ar=new PdfPCell(new Paragraph(date5t,Tahoma));
            date5ar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  date5ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(date5ar);
            
           
            PdfPCell num6ar=new PdfPCell(new Paragraph("6",Tahoma));
            num6ar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  num6ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(num6ar);
            
          
            PdfPCell payment6ar=new PdfPCell(new Paragraph(payment6,Tahoma));
            payment6ar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  payment6ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(payment6ar);
            
            
            PdfPCell date6ar=new PdfPCell(new Paragraph(date6t,Tahoma));
            date6ar.setHorizontalAlignment(Element.ALIGN_CENTER);
           // date6ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(date6ar);
            
            
            PdfPCell num7ar=new PdfPCell(new Paragraph("7",Tahoma));
            num7ar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  num7ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(num7ar);
            
           
            PdfPCell payment7ar=new PdfPCell(new Paragraph(payment7,Tahoma));
            payment7ar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  payment7ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(payment7ar);
            
            
            PdfPCell date7ar=new PdfPCell(new Paragraph(date7t,Tahoma));
            date7ar.setHorizontalAlignment(Element.ALIGN_CENTER);
           // date7ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(date7ar);
            
             
            PdfPCell num8ar=new PdfPCell(new Paragraph("8",Tahoma));
            num8ar.setHorizontalAlignment(Element.ALIGN_CENTER);
           // num8ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(num8ar);
            
            
            PdfPCell payment8ar=new PdfPCell(new Paragraph(payment8,Tahoma));
            payment8ar.setHorizontalAlignment(Element.ALIGN_CENTER);
           // payment8ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(payment8ar);
            
            
            PdfPCell date8ar=new PdfPCell(new Paragraph(date8t,Tahoma));
            date8ar.setHorizontalAlignment(Element.ALIGN_CENTER);
           // date8ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(date8ar);
            
            
            PdfPCell num9ar=new PdfPCell(new Paragraph("9",Tahoma));
            num9ar.setHorizontalAlignment(Element.ALIGN_CENTER);
          //  num9ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(num9ar);
            
            
            PdfPCell payment9ar=new PdfPCell(new Paragraph(payment9,Tahoma));
            payment9ar.setHorizontalAlignment(Element.ALIGN_CENTER);
           // payment9ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(payment9ar);
            
          
            PdfPCell date9ar=new PdfPCell(new Paragraph(date9t,Tahoma));
            date9ar.setHorizontalAlignment(Element.ALIGN_CENTER);
           // date9ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(date9ar);
            
            
            PdfPCell num10ar=new PdfPCell(new Paragraph("10",Tahoma));
            num10ar.setHorizontalAlignment(Element.ALIGN_CENTER);
         //   num10ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(num10ar);
            
        
            PdfPCell payment10ar=new PdfPCell(new Paragraph(payment10,Tahoma));
            payment10ar.setHorizontalAlignment(Element.ALIGN_CENTER);
         //   payment10ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(payment10ar);
            
            
            PdfPCell date10ar=new PdfPCell(new Paragraph(date10t,Tahoma));
            date10ar.setHorizontalAlignment(Element.ALIGN_CENTER);
         //   date10ar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(date10ar);
            
            
            PdfPCell numsumar=new PdfPCell(new Paragraph(" ",Tahoma));
            numsumar.setHorizontalAlignment(Element.ALIGN_CENTER);
         //   numsumar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(numsumar);
            
            
            PdfPCell sumar=new PdfPCell(new Paragraph("مجموع الدفعات",Tahoma));
            sumar.setHorizontalAlignment(Element.ALIGN_CENTER);
         //   sumar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(sumar);
            
         
            PdfPCell sumv=new PdfPCell(new Paragraph(sumt,Tahoma));
            sumv.setHorizontalAlignment(Element.ALIGN_CENTER);
         //   sumv.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(sumv);
            
           doc.add(bodytable);
            doc.close();            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "لايمكن اعداد التقرير برجاء اغلاق report.pdf");
        }
         if (Desktop.isDesktopSupported()) {
    try {
        File myFile = new File("C:\\report\\cont_report\\report.pdf");
        Desktop.getDesktop().open(myFile);
    }
    catch (IOException ex) {
        JOptionPane.showMessageDialog(null, "لايمكن فتح "
                + "report.pdf");}
         }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(all_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(all_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(all_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(all_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new all_emp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable all_proj_jtable;
    private javax.swing.JTextField cont_name_txt;
    private javax.swing.JTextField cont_phone_txt;
    public javax.swing.JComboBox contractor_compo;
    public static javax.swing.JLabel cust_name;
    public static javax.swing.JLabel custphone_txt;
    private javax.swing.JTextField date1;
    private javax.swing.JTextField date10;
    private javax.swing.JTextField date2;
    private javax.swing.JTextField date3;
    private javax.swing.JTextField date4;
    private javax.swing.JTextField date5;
    private javax.swing.JTextField date6;
    private javax.swing.JTextField date7;
    private javax.swing.JTextField date8;
    private javax.swing.JTextField date9;
    private javax.swing.JButton del_details;
    public static javax.swing.JLabel ename_txt;
    public static javax.swing.JLabel eserial_txt;
    private javax.swing.JTextField hours_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton new_details;
    private javax.swing.JLabel p_serial_txt;
    private javax.swing.JTextField payment10_txt;
    private javax.swing.JTextField payment1_txt;
    private javax.swing.JTextField payment2_txt;
    private javax.swing.JTextField payment3_txt;
    private javax.swing.JTextField payment4_txt;
    private javax.swing.JTextField payment5_txt;
    private javax.swing.JTextField payment6_txt;
    private javax.swing.JTextField payment7_txt;
    private javax.swing.JTextField payment8_txt;
    private javax.swing.JTextField payment9_txt;
    public static javax.swing.JLabel proj_name;
    public static javax.swing.JLabel pserial_txt;
    private javax.swing.JTable sum_tbl;
    private javax.swing.JTextField sum_txt;
    // End of variables declaration//GEN-END:variables
}
