/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package decoration;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import static decoration.project_contractor.Tahoma;
import static decoration.project_state.fontSize;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author salah
 */
public class res_details extends javax.swing.JFrame {

    /**
     * Creates new form res_details
     */
    public res_details() {
        initComponents();
        fill_combo();
        tag_combo();
    }
    public static Font Tahoma = FontFactory.getFont("c://windows//fonts//tahoma.ttf",
                            BaseFont.IDENTITY_H,fontSize);
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        price_txt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        s_name_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        id_txt = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        payed_txt = new javax.swing.JTextField();
        tag_txt = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        proj_name = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        custphone_txt = new javax.swing.JLabel();
        eserial_txt = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cust_name = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ename_txt = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pserial_txt = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        remaining_txt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sum_txt = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        payed_sum_txt = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        price_txt.setText("0.0");

        jButton3.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 0));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\delete2.jpg")); // NOI18N
        jButton3.setText("حذف");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 153, 0));
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\floppy_disk.jpg")); // NOI18N
        jButton5.setText("حفظ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel1.setText("الصروفات");

        jLabel2.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel2.setText("Tag");

        jButton2.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 0));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\folder_new.jpg")); // NOI18N
        jButton2.setText("جديد");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel3.setText("القيمة");

        jLabel6.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel6.setText("ID");

        id_txt.setText("...");

        jLabel15.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel15.setText("المدفوع");

        payed_txt.setText("0.0");
        payed_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payed_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(s_name_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addComponent(tag_txt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(payed_txt)
                            .addComponent(price_txt))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(s_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(price_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tag_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(payed_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "ترتيب", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Simplified Arabic", 0, 14))); // NOI18N

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel4.setText("Tag");

        jButton6.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 153, 0));
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\folder_refresh.jpg")); // NOI18N
        jButton6.setText("reset");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 153, 0));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\document_text.jpg")); // NOI18N
        jButton4.setText("طباعة");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 153, 0));
        jButton7.setText("طباعه المقاول والخامات");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "المشروع", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 11))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("تليفون العميل");

        jLabel9.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("اسم العميل");

        jLabel12.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("اسم الموظف المسئول");

        jLabel11.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("رقم الموظف");

        jLabel7.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("اسم المشروع");

        jLabel13.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("رقم المشروع");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(22, 22, 22)
                        .addComponent(ename_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(74, 74, 74)
                        .addComponent(pserial_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(112, 112, 112)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(52, 52, 52)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(proj_name, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(custphone_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9))
                .addGap(56, 56, 56)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cust_name, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(eserial_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(184, 184, 184))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cust_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(proj_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pserial_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(ename_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(eserial_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(custphone_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "الجموع"));

        remaining_txt.setText("0.0");

        jLabel5.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel5.setText("المدفوع");

        jLabel8.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel8.setText("الاجمالى");

        sum_txt.setText("0.0");

        jLabel14.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel14.setText("المتبقى");

        payed_sum_txt.setText("0.0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(5, 5, 5))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sum_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                            .addComponent(payed_sum_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(28, 28, 28)
                        .addComponent(remaining_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(payed_sum_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sum_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(remaining_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jButton8.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 153, 0));
        jButton8.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\document_text.jpg")); // NOI18N
        jButton8.setText("طباعه الكل");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\folder_refresh.jpg")); // NOI18N
        jButton1.setText("refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(366, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton8)
                        .addGap(44, 44, 44)
                        .addComponent(jButton1)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\close.png")); // NOI18N
        jMenuItem1.setText("اغلاق");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\exit.jpg")); // NOI18N
        jMenuItem2.setText("اغلاق البرنامج");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1275, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        selecting_db();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new_rec();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        insert_db();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        getting_data();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        delete_data();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        selecting_db();
        
        fill_combo();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        sort_c();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        print_all();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        sort_print();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void payed_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payed_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payed_txtActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        print_wcont();
    }//GEN-LAST:event_jButton7ActionPerformed
    public void close(){
        

        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEve­ntQueue().postEvent(winClosingEvent);
     }
    /**
     * @param args the command line arguments
     */
    //sorting by combo box value 
    public void new_rec(){
         s_name_txt.setText(null);
        price_txt.setText("0.0");
        //tag_txt.setText(null);
        id_txt.setText("...");
        payed_txt.setText("0.0");
        payed_sum_txt.setText("0.0");
        sum_txt.setText("0.0");
        remaining_txt.setText("0.0");
}
    public void sort_c(){
        Connection c = null;
        Statement s = null;
        ResultSet rs = null;
        String tagt=jComboBox1.getSelectedItem().toString();
        String pserial=pserial_txt.getText();
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            if(pserial==""){
                //if this if and else removed it will show error on openning jframe that their an error in sql statement as pserial value will be null
                //so don't remove it
            }else{
            String sql_select="select id,s_name as 'الصروفات',price as 'القيمة',payed as 'المدفوع' from details_res "
                    + "where p_serial="+pserial+" and tag='"+tagt+"' ";
            rs=s.executeQuery(sql_select);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            String sum="select sum(price) as 'price' , sum(payed) as'payed' from details_res where p_serial="+pserial+" and tag='"+tagt+"' ";
            rs=s.executeQuery(sum);
            if(rs.next()){
                String sprice=rs.getString("price");
                sum_txt.setText(sprice);
                String spayed=rs.getString("payed");
                payed_sum_txt.setText(spayed);
            }
            double payedt=Double.parseDouble(payed_sum_txt.getText());
            double totalt=Double.parseDouble(sum_txt.getText());
            double m=totalt-payedt;
            remaining_txt.setText(Double.toString(m));
            s.close();
            rs.close();
            c.commit();
            c.close();}
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "خطا برجاء المحاوله لاحقا");
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }
    //selecting data from jtable in jtextfields
    public void getting_data(){
        Connection c = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            //s=c.createStatement();
            int row=jTable1.getSelectedRow();
            String idt=(jTable1.getModel().getValueAt(row, 0).toString());
            String sql_select="select * from details_res where id="+idt+" ";
             pst=(PreparedStatement) c.prepareStatement(sql_select);
             rs=pst.executeQuery();
             if(rs.next()){
                 String idtt=rs.getString("id");
                 id_txt.setText(idtt);
                 
                 String s_namet=rs.getString("s_name");
                 s_name_txt.setText(s_namet);
                 
                 String tagt=rs.getString("tag");
                 tag_txt.setSelectedItem(tagt);
                 
                 String pricet=rs.getString("price");
                 price_txt.setText(pricet);
                 
                 String payedt=rs.getString("payed");
                 payed_txt.setText(payedt);
             }
             rs.close();
             pst.close();
             c.commit();
             c.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "خطأ برجاء المحاوله لاحقا");
        }
         finally{
            try{
               
          //  rs.close();
            pst.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }
    
    //inserting new value or update existing one
    public void insert_db(){
        String pserial=pserial_txt.getText();
        String s_namet=s_name_txt.getText();
        String tagt=tag_txt.getSelectedItem().toString();
        String pricet=price_txt.getText();
        String idt=id_txt.getText();
        String payedt=payed_txt.getText();
        Connection c = null;
        Statement s = null;
       
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
          //  String sql_select="select * from details_res where p_serial="+pserial+" and s_name = '"+s_namet+"' and tag='"+tagt+"' and price= "+pricet+" ";
           if(idt == "..."){
               String sql_insert="insert into details_res (p_serial, s_name, tag, price,payed) values ("+pserial+", '"+s_namet+"', '"+tagt+"',"+pricet+","+payedt+") ";
               s.executeUpdate(sql_insert);
           }else{
               String sql_update="update details_res set s_name='"+s_namet+"', tag='"+tagt+"', price="+pricet+", payed="+payedt+" where id="+idt+" and p_serial="+pserial+" ";
               s.executeUpdate(sql_update);
           } 
            s.close();
            c.commit();
            c.close();
            selecting_db();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "خطأ لايمكن الاضافة او التعديل");
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }
    //delete data 
    public void delete_data(){
        Connection c=null;
        Statement s=null;
        String pserial=pserial_txt.getText();
        String idt=id_txt.getText();
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            String sql_delete="delete from details_res where id="+idt+" and p_serial="+pserial+" ";
            s.executeUpdate(sql_delete);
            s.close();
            c.commit();
            c.close();
            new_rec();
            selecting_db();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "خطأ لايمكن الحذف");
        
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }

    //select from db 
    public void selecting_db(){
        Connection c=null;
        Statement s=null;
        ResultSet rs=null;
        String pserial=pserial_txt.getText();
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            String sql_select="select id,s_name as 'الصروفات',price as 'القيمة', payed as 'المتبقى' from details_res where p_serial = "+pserial+" ";
            jTable1.setModel(DbUtils.resultSetToTableModel(s.executeQuery(sql_select)));
            
            s.close();
            c.commit();
            c.close();
            total();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "خطأ!!! يرجى المحاوله لاحقا");
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
        
    }
    //combo box fill with data 
    public void fill_combo(){
        Connection c=null;
        Statement s=null;
        ResultSet rs=null;
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            String sql="select * from details_res ";
            rs=s.executeQuery(sql);
            while(rs.next()){
                String tagt=rs.getString("tag");
                jComboBox1.addItem(tagt);
            }
            rs.close();
            s.close();
            c.commit();
            c.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "خطأ");
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }
    //fill tag combo
    public void tag_combo(){
        Connection c=null;
        Statement s=null;
        ResultSet rs=null;
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            String sql="select cont from cont_combo;";
            rs=s.executeQuery(sql);
            while(rs.next()){
                String pname =rs.getString("cont");
                tag_txt.addItem(pname);
               
            }
            rs.close();
            s.close();
            c.commit();
            c.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "خطأ");
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }
    //get total 
    public void total(){
        Connection c=null;
        Statement s=null;
        ResultSet rs=null;
        String pserial=pserial_txt.getText();
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            String sum_price="select sum(price) as 'sum' from details_res where p_serial="+pserial+" ";
            rs=s.executeQuery(sum_price);
            if(rs.next()){
                String sumt=rs.getString("sum");
                sum_txt.setText(sumt);
            }
            String sum_payed="select sum(payed) as 'payed' from details_res where p_serial="+pserial+" ";
            rs=s.executeQuery(sum_payed);
            if(rs.next()){
                String payedt=rs.getString("payed");
                payed_sum_txt.setText(payedt);
            }
            String payedv = payed_sum_txt.getText();
            String sumv = sum_txt.getText();
            if(payedv == null || sumv == null){
                
            }else{
            double payedt=Double.parseDouble(payed_sum_txt.getText());
            double totalt=Double.parseDouble(sum_txt.getText());
            double m=totalt-payedt;
            remaining_txt.setText(Double.toString(m));
            }
            s.close();
            rs.close();
            c.commit();
            c.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "خطا لايمكن الجمع");
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
    }
    //payed text
//    public void payed_insert(){
//       Connection c=null;
//        Statement s=null;
//        ResultSet rs=null;
//        String pserial=pserial_txt.getText();
//        String payedt=payed_txt.getText();
//        try{
//            Class.forName("org.sqlite.JDBC");
//            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
//            c.setAutoCommit(false);
//            s=c.createStatement();
//            String select ="select * from total_res where p_serial="+pserial+" ";
//            rs=s.executeQuery(select);
//            if(rs.next()){
//                String update="update total_res set payed="+payedt+" where p_serial="+pserial+" ";
//                s.executeUpdate(update);
//            }else{
//                String insert="insert into total_res(p_serial,payed) values("+pserial+","+payedt+")";
//                s.executeUpdate(insert);
//            }
//           
//            s.close();
//            rs.close();
//            c.commit();
//            c.close();
//            selecting_db();
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(null, e);
//        }
//    }
    public void print_all(){
        String cnamet = cust_name.getText();
        String pserial=pserial_txt.getText();
        String sumt=sum_txt.getText();
        String payedt=payed_sum_txt.getText();
        String remaint=remaining_txt.getText();
        
        Document doc=new Document();
        Connection c =null;
        Statement s =null;
        ResultSet rs=null;
        
        try{
           // String serialt=pserial_txt.getText();
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            ////////////////////////////////////////////////////////////////
            PdfWriter.getInstance(doc, new FileOutputStream("C:\\report\\res_report\\report.pdf"));
            doc.open();
            Image img=Image.getInstance("C:\\report\\all_emp\\ModernDesignlogo.jpg");
            //img.setAbsolutePosition(30f, 700f);
            doc.add(img);
            PdfPTable headtable=new PdfPTable(1);
            headtable.setRunDirection(PdfWriter.RUN_DIRECTION_RTL);
            PdfPCell headcell=new PdfPCell();
            headcell.setBorder(Rectangle.NO_BORDER);
         
            
            PdfPCell cnamec=new PdfPCell(new Paragraph(cnamet,Tahoma));
           // cnamec.setBackgroundColor(BaseColor.YELLOW);
            cnamec.setHorizontalAlignment(Element.ALIGN_CENTER);
            cnamec.setBorder(Rectangle.NO_BORDER);
            headtable.addCell(cnamec);
            doc.add(headtable);
            
            doc.add(new Paragraph("\n"));
            
            PdfPTable dettbl=new PdfPTable(2);
            dettbl.setRunDirection(PdfWriter.RUN_DIRECTION_RTL);
            PdfPCell detcell=new PdfPCell();
            //detcell.setBorder(Rectangle.NO_BORDER);
            
//            Paragraph nametitle;
//            nametitle= new Paragraph("الصروفات" ,Tahoma);
//            nametitle.setAlignment(PdfPCell.ALIGN_LEFT);
//            detcell.setBackgroundColor(BaseColor.YELLOW);
//            dettbl.addCell(nametitle);
            
            PdfPCell cell=new PdfPCell(new Paragraph("الصروفات",Tahoma));
            cell.setBackgroundColor(BaseColor.YELLOW);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(cell);
            
          
            
            PdfPCell cellprice=new PdfPCell(new Paragraph("السعر",Tahoma));
            cellprice.setBackgroundColor(BaseColor.YELLOW);
            cellprice.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(cellprice);
            
            String sql_select = "select s_name, price from details_res where p_serial="+pserial+" ";
            rs=s.executeQuery(sql_select);
            while(rs.next()){
                String sname=rs.getString("s_name");
                String price = rs.getString("price");
            
               PdfPCell cellsname=new PdfPCell(new Paragraph(sname,Tahoma));
            cellsname.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(cellsname);
            
          
            
                PdfPCell pricev=new PdfPCell(new Paragraph(price,Tahoma));
            pricev.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(pricev); 
               // doc.add(dettbl);
            }
            
             PdfPCell empty1=new PdfPCell(new Paragraph(" ",Tahoma));
            empty1.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(empty1); 
            
             PdfPCell empty2=new PdfPCell(new Paragraph(" ",Tahoma));
            empty2.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(empty2); 
              
            
            
                PdfPCell sumar=new PdfPCell(new Paragraph("الاجمالى",Tahoma));
            sumar.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(sumar); 
            
          
            
                
                PdfPCell sumv=new PdfPCell(new Paragraph(sumt,Tahoma));
            sumv.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(sumv); 
                
             
                PdfPCell payedar=new PdfPCell(new Paragraph("المدفوع",Tahoma));
            payedar.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(payedar); 
            
          
            
                PdfPCell payedv=new PdfPCell(new Paragraph(payedt,Tahoma));
            payedv.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(payedv); 
                
               
                PdfPCell remainar=new PdfPCell(new Paragraph("المتبقى",Tahoma));
            remainar.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(remainar); 
            
          
                PdfPCell remainv=new PdfPCell(new Paragraph(remaint,Tahoma));
            remainv.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(remainv); 
               // doc.add(dettbl);
            /////////////////////////////////////////
            doc.add(dettbl);
            doc.close();            
            
            rs.close();
            s.close();
            c.commit();
            c.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "برجاء اغلاق report.pdf");
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
         if (Desktop.isDesktopSupported()) {
    try {
        File myFile = new File("C:\\report\\res_report\\report.pdf");
        Desktop.getDesktop().open(myFile);
    }
    catch (IOException ex) {
        JOptionPane.showMessageDialog(null, "لايمكن فتح "
                + "report.pdf");}
         }
    }
    //print contractor 
    public void print_wcont(){
        
        Connection c =null;
        Statement s = null;
        ResultSet rs=null;
        String sumt=sum_txt.getText();
        String payedt=payed_sum_txt.getText();
        String remaint=remaining_txt.getText();
        String pserialt=pserial_txt.getText();
        String tagt=jComboBox1.getSelectedItem().toString();
        String cnamet=cust_name.getText();
        Document doc=new Document();
        try{
             Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            /////////////////////////////
            PdfWriter.getInstance(doc, new FileOutputStream("C:\\report\\res_report\\sort\\report.pdf"));
            doc.open();
            Image img=Image.getInstance("C:\\report\\all_emp\\ModernDesignlogo.jpg");
            //img.setAbsolutePosition(30f, 700f);
            doc.add(img);
            PdfPTable headtable=new PdfPTable(1);
            headtable.setRunDirection(PdfWriter.RUN_DIRECTION_RTL);
            PdfPCell headcell=new PdfPCell();
            headcell.setBorder(Rectangle.NO_BORDER);
         
            
            PdfPCell cnamec=new PdfPCell(new Paragraph(cnamet,Tahoma));
         //   cnamec.setBackgroundColor(BaseColor.YELLOW);
            cnamec.setHorizontalAlignment(Element.ALIGN_CENTER);
            cnamec.setBorder(Rectangle.NO_BORDER);
            headtable.addCell(cnamec);
            doc.add(headtable);
            
            doc.add(new Paragraph("\n"));
              PdfPTable dettbl=new PdfPTable(2);
            dettbl.setRunDirection(PdfWriter.RUN_DIRECTION_RTL);
            PdfPCell detcell=new PdfPCell();
            
            
            PdfPCell cell=new PdfPCell(new Paragraph("الصروفات",Tahoma));
            cell.setBackgroundColor(BaseColor.YELLOW);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(cell);
            
          
            
            PdfPCell cellprice=new PdfPCell(new Paragraph("السعر",Tahoma));
            cellprice.setBackgroundColor(BaseColor.YELLOW);
            cellprice.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(cellprice);
            ///////////////////////////////
            String sql_select="select * from details_res where p_serial="+pserialt+" and tag='"+tagt+"' ";
            rs=s.executeQuery(sql_select);
            while(rs.next()){
                 String sname=rs.getString("s_name");
                String price = rs.getString("price");
            
               PdfPCell cellsname=new PdfPCell(new Paragraph(sname,Tahoma));
               cellsname.setHorizontalAlignment(Element.ALIGN_CENTER);
               dettbl.addCell(cellsname);
            
          
            
                PdfPCell pricev=new PdfPCell(new Paragraph(price,Tahoma));
                pricev.setHorizontalAlignment(Element.ALIGN_CENTER);
                dettbl.addCell(pricev); 
            }
            
             PdfPCell empty1=new PdfPCell(new Paragraph(" ",Tahoma));
            empty1.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(empty1); 
            
             PdfPCell empty2=new PdfPCell(new Paragraph(" ",Tahoma));
            empty2.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(empty2); 
              
            
            
                PdfPCell sumar=new PdfPCell(new Paragraph("الاجمالى",Tahoma));
            sumar.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(sumar); 
            
          
            
                
                PdfPCell sumv=new PdfPCell(new Paragraph(sumt,Tahoma));
            sumv.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(sumv); 
                
             
                PdfPCell payedar=new PdfPCell(new Paragraph("المدفوع",Tahoma));
            payedar.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(payedar); 
            
          
            
                PdfPCell payedv=new PdfPCell(new Paragraph(payedt,Tahoma));
            payedv.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(payedv); 
                
               
                PdfPCell remainar=new PdfPCell(new Paragraph("المتبقى",Tahoma));
            remainar.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(remainar); 
            
          
                PdfPCell remainv=new PdfPCell(new Paragraph(remaint,Tahoma));
            remainv.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(remainv); 
               // doc.add(dettbl);
            /////////////////////////////////////////
            doc.add(dettbl);
            //contractor print
            ////////////////////////////////////////////////////////////////////
            doc.add(new Paragraph("\n"));
            doc.add(new Paragraph("\n"));
            doc.add(new Paragraph("\n"));
            PdfPTable headtable1=new PdfPTable(1);
            headtable1.setRunDirection(PdfWriter.RUN_DIRECTION_RTL);
           
            
            PdfPCell cellpayedn=new PdfPCell(new Paragraph("دفعات المقاول",Tahoma));
            cellpayedn.setBorder(Rectangle.NO_BORDER);
            cellpayedn.setHorizontalAlignment(Element.ALIGN_CENTER);
            headtable1.addCell(cellpayedn);
            
           
            doc.add(headtable1);
            doc.add(new Paragraph("\n"));
            
            PdfPTable bodytable=new PdfPTable(3);
            bodytable.setRunDirection(PdfWriter.RUN_DIRECTION_RTL);
            PdfPCell bodycell=new PdfPCell();
           bodycell.setBorder(Rectangle.ALIGN_CENTER);
           
           bodytable.setWidths(new int[]{2,2,1});
          
             PdfPCell numar=new PdfPCell(new Paragraph("الرقم",Tahoma));
            numar.setBackgroundColor(BaseColor.YELLOW);
            numar.setHorizontalAlignment(Element.ALIGN_CENTER);
            //numar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(numar);
            
            
            PdfPCell paymentar=new PdfPCell(new Paragraph("الدفعات",Tahoma));
            paymentar.setBackgroundColor(BaseColor.YELLOW);
            paymentar.setHorizontalAlignment(Element.ALIGN_CENTER);
            //paymentar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(paymentar);
            
           
            PdfPCell datear=new PdfPCell(new Paragraph("التاريخ",Tahoma));
            datear.setBackgroundColor(BaseColor.YELLOW);
            datear.setHorizontalAlignment(Element.ALIGN_CENTER);
           // datear.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(datear);
            String sql_s="select pc.payment1,pc.payment2,pc.payment3,pc.payment4,pc.payment5,pc.payment6,pc.payment7,pc.payment8,pc.payment9,pc.payment10,cd.date1,cd.date2,cd.date3,cd.date4,cd.date5,cd.date6,cd.date7,cd.date8,cd.date9,cd.date10 "
                    + "from proj_contractor pc, cont_date cd where pc.p_serial="+pserialt+" and cd.p_serial="+pserialt+" and pc.tag='"+tagt+"' and cd.tag='"+tagt+"'  ";
            rs=s.executeQuery(sql_s);
            
            while(rs.next()){
              
                 
            PdfPCell ar1=new PdfPCell(new Paragraph("1",Tahoma));
            ar1.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(ar1);
            
                String payment1=rs.getString("payment1");
                
                PdfPCell payment1t=new PdfPCell(new Paragraph(payment1,Tahoma));
            payment1t.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(payment1t);
            
                String date1=rs.getString("date1");
                PdfPCell date1t=new PdfPCell(new Paragraph(date1,Tahoma));
            date1t.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(date1t);
                
                 
            PdfPCell ar2=new PdfPCell(new Paragraph("2",Tahoma));
            ar2.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(ar2);
            
            String payment2=rs.getString("payment2");
            PdfPCell payment2t=new PdfPCell(new Paragraph(payment2,Tahoma));
            payment2t.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(payment2t);
            
            String date2=rs.getString("date2");
            PdfPCell date2t=new PdfPCell(new Paragraph(date2,Tahoma));
            date2t.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(date2t);
                
                 
            PdfPCell ar3=new PdfPCell(new Paragraph("3",Tahoma));
            ar3.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(ar3);
            
            String payment3=rs.getString("payment3");
            PdfPCell payment3t=new PdfPCell(new Paragraph(payment3,Tahoma));
            payment3t.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(payment3t);
            
            String date3=rs.getString("date3");
            PdfPCell date3t=new PdfPCell(new Paragraph(date3,Tahoma));
            date3t.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(date3t);
                
                 
            PdfPCell ar4=new PdfPCell(new Paragraph("4",Tahoma));
            ar4.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(ar4);
            
            String payment4=rs.getString("payment4");
            PdfPCell payment4t=new PdfPCell(new Paragraph(payment4,Tahoma));
            payment4t.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(payment4t);
            
            String date4=rs.getString("date4");
            PdfPCell date4t=new PdfPCell(new Paragraph(date4,Tahoma));
            date4t.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(date4t);
                
            PdfPCell ar5=new PdfPCell(new Paragraph("5",Tahoma));
            ar5.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(ar5);
            
            String payment5=rs.getString("payment5");
            PdfPCell payment5t=new PdfPCell(new Paragraph(payment5,Tahoma));
            payment5t.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(payment5t);
            
            String date5=rs.getString("date5");
            PdfPCell date5t=new PdfPCell(new Paragraph(date5,Tahoma));
            date5t.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(date5t);
                
            PdfPCell ar6=new PdfPCell(new Paragraph("6",Tahoma));
            ar6.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(ar6);
            
            String payment6=rs.getString("payment6");
            PdfPCell payment6t=new PdfPCell(new Paragraph(payment6,Tahoma));
            payment6t.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(payment6t);
            
            String date6=rs.getString("date6");
            PdfPCell date6t=new PdfPCell(new Paragraph(date6,Tahoma));
            date6t.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(date6t);
                
            PdfPCell ar7=new PdfPCell(new Paragraph("7",Tahoma));
            ar7.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(ar7);
            
            String payment7=rs.getString("payment7");
            PdfPCell payment7t=new PdfPCell(new Paragraph(payment7,Tahoma));
            payment7t.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(payment7t);
            
            String date7=rs.getString("date7");
            PdfPCell date7t=new PdfPCell(new Paragraph(date7,Tahoma));
            date7t.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(date7t);
            
                
            PdfPCell ar8=new PdfPCell(new Paragraph("8",Tahoma));
            ar8.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(ar8);
            
            String payment8=rs.getString("payment8");
            PdfPCell payment8t=new PdfPCell(new Paragraph(payment8,Tahoma));
            payment8t.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(payment8t);
            
            String date8=rs.getString("date8");
            PdfPCell date8t=new PdfPCell(new Paragraph(date8,Tahoma));
            date8t.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(date8t);
                
                 
            PdfPCell ar9=new PdfPCell(new Paragraph("9",Tahoma));
            ar9.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(ar9);
            
            String payment9=rs.getString("payment9");
            PdfPCell payment9t=new PdfPCell(new Paragraph(payment9,Tahoma));
            payment9t.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(payment9t);
            
            String date9=rs.getString("date9");
            PdfPCell date9t=new PdfPCell(new Paragraph(date9,Tahoma));
            date9t.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(date9t);
                
            PdfPCell ar10=new PdfPCell(new Paragraph("10",Tahoma));
            ar10.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(ar10);
            
            String payment10=rs.getString("payment10");
            PdfPCell payment10t=new PdfPCell(new Paragraph(payment10,Tahoma));
            payment10t.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(payment10t);
            
            String date10=rs.getString("date10");
            PdfPCell date10t=new PdfPCell(new Paragraph(date10,Tahoma));
            date10t.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(date10t);
                
            }
           
            PdfPCell numsumar=new PdfPCell(new Paragraph(" ",Tahoma));
            numsumar.setHorizontalAlignment(Element.ALIGN_CENTER);
            bodytable.addCell(numsumar);
            
            String sql_sum="Select payment1+payment2+payment3+payment4+payment5+payment6+payment7+payment8+payment9+payment10 as 'sum' "
                    + "from proj_contractor where p_serial="+pserialt+" and tag='"+tagt+"' ";
            rs=s.executeQuery(sql_sum);
            if(rs.next()){
                String sumtt=rs.getString("sum");
                PdfPCell sumpar=new PdfPCell(new Paragraph("مجموع الدفعات",Tahoma));
            sumpar.setHorizontalAlignment(Element.ALIGN_CENTER);
         //   sumar.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(sumpar);
            
         
            PdfPCell sump=new PdfPCell(new Paragraph(sumtt,Tahoma));
            sump.setHorizontalAlignment(Element.ALIGN_CENTER);
         //   sumv.setBorder(Rectangle.NO_BORDER);
            bodytable.addCell(sump);
            }
            
            doc.add(bodytable);
            
            
            doc.close();            
            

            rs.close();
            s.close();
            c.commit();
            c.close();
            
        }catch(Exception e){
           //  JOptionPane.showMessageDialog(null, e);
           JOptionPane.showMessageDialog(null, "برجاء اغلاق report.pdf");
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
        try {
        File myFile = new File("C:\\report\\res_report\\sort\\report.pdf");
        Desktop.getDesktop().open(myFile);
    }
    catch (IOException ex) {
        JOptionPane.showMessageDialog(null, "لايمكن فتح "
                + "report.pdf");}
    }
    //print sorted list 
    public void sort_print(){
        Connection c =null;
        Statement s = null;
        ResultSet rs=null;
        String sumt=sum_txt.getText();
        String payedt=payed_sum_txt.getText();
        String remaint=remaining_txt.getText();
        String pserialt=pserial_txt.getText();
        String tagt=jComboBox1.getSelectedItem().toString();
        String cnamet=cust_name.getText();
        Document doc=new Document();
        try{
             Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            /////////////////////////////
            PdfWriter.getInstance(doc, new FileOutputStream("C:\\report\\res_report\\sort\\report.pdf"));
            doc.open();
            Image img=Image.getInstance("C:\\report\\all_emp\\ModernDesignlogo.jpg");
            //img.setAbsolutePosition(30f, 700f);
            doc.add(img);
            PdfPTable headtable=new PdfPTable(1);
            headtable.setRunDirection(PdfWriter.RUN_DIRECTION_RTL);
            PdfPCell headcell=new PdfPCell();
            headcell.setBorder(Rectangle.NO_BORDER);
         
            
            PdfPCell cnamec=new PdfPCell(new Paragraph(cnamet,Tahoma));
         //   cnamec.setBackgroundColor(BaseColor.YELLOW);
            cnamec.setHorizontalAlignment(Element.ALIGN_CENTER);
            cnamec.setBorder(Rectangle.NO_BORDER);
            headtable.addCell(cnamec);
            doc.add(headtable);
            
            doc.add(new Paragraph("\n"));
              PdfPTable dettbl=new PdfPTable(2);
            dettbl.setRunDirection(PdfWriter.RUN_DIRECTION_RTL);
            PdfPCell detcell=new PdfPCell();
            
            
            PdfPCell cell=new PdfPCell(new Paragraph("الصروفات",Tahoma));
            cell.setBackgroundColor(BaseColor.YELLOW);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(cell);
            
          
            
            PdfPCell cellprice=new PdfPCell(new Paragraph("السعر",Tahoma));
            cellprice.setBackgroundColor(BaseColor.YELLOW);
            cellprice.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(cellprice);
            ///////////////////////////////
            String sql_select="select * from details_res where p_serial="+pserialt+" and tag='"+tagt+"' ";
            rs=s.executeQuery(sql_select);
            while(rs.next()){
                 String sname=rs.getString("s_name");
                String price = rs.getString("price");
            
               PdfPCell cellsname=new PdfPCell(new Paragraph(sname,Tahoma));
               cellsname.setHorizontalAlignment(Element.ALIGN_CENTER);
               dettbl.addCell(cellsname);
            
          
            
                PdfPCell pricev=new PdfPCell(new Paragraph(price,Tahoma));
                pricev.setHorizontalAlignment(Element.ALIGN_CENTER);
                dettbl.addCell(pricev); 
            }
            
             PdfPCell empty1=new PdfPCell(new Paragraph(" ",Tahoma));
            empty1.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(empty1); 
            
             PdfPCell empty2=new PdfPCell(new Paragraph(" ",Tahoma));
            empty2.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(empty2); 
              
            
            
                PdfPCell sumar=new PdfPCell(new Paragraph("الاجمالى",Tahoma));
            sumar.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(sumar); 
            
          
            
                
                PdfPCell sumv=new PdfPCell(new Paragraph(sumt,Tahoma));
            sumv.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(sumv); 
                
             
                PdfPCell payedar=new PdfPCell(new Paragraph("المدفوع",Tahoma));
            payedar.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(payedar); 
            
          
            
                PdfPCell payedv=new PdfPCell(new Paragraph(payedt,Tahoma));
            payedv.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(payedv); 
                
               
                PdfPCell remainar=new PdfPCell(new Paragraph("المتبقى",Tahoma));
            remainar.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(remainar); 
            
          
                PdfPCell remainv=new PdfPCell(new Paragraph(remaint,Tahoma));
            remainv.setHorizontalAlignment(Element.ALIGN_CENTER);
            dettbl.addCell(remainv); 
               // doc.add(dettbl);
            /////////////////////////////////////////
            doc.add(dettbl);
            doc.close();            
            

            rs.close();
            s.close();
            c.commit();
            c.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "برجاء اغلاق report.pdf");
        }
         finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
            
        }
        try {
        File myFile = new File("C:\\report\\res_report\\sort\\report.pdf");
        Desktop.getDesktop().open(myFile);
    }
    catch (IOException ex) {
        JOptionPane.showMessageDialog(null, "لايمكن فتح "
                + "report.pdf");}
         }


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(res_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(res_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(res_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(res_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new res_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel cust_name;
    public static javax.swing.JLabel custphone_txt;
    public static javax.swing.JLabel ename_txt;
    public static javax.swing.JLabel eserial_txt;
    private javax.swing.JLabel id_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel payed_sum_txt;
    private javax.swing.JTextField payed_txt;
    private javax.swing.JTextField price_txt;
    public static javax.swing.JLabel proj_name;
    public static javax.swing.JLabel pserial_txt;
    private javax.swing.JLabel remaining_txt;
    private javax.swing.JTextField s_name_txt;
    private javax.swing.JLabel sum_txt;
    private javax.swing.JComboBox tag_txt;
    // End of variables declaration//GEN-END:variables
}
