/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package decoration;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author salah
 */
public class users extends javax.swing.JFrame {

    /**
     * Creates new form users
     */
    public users() {
        initComponents();
        db_show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        user_tbl = new javax.swing.JTable();
        user_txt = new javax.swing.JTextField();
        pass_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        userid_txt = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        user_tbl.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        user_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        user_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_tblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(user_tbl);

        user_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_txtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel1.setText("اسم المستخدم");

        jLabel2.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel2.setText("كلمة السر");

        jButton1.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\floppy_disk.jpg")); // NOI18N
        jButton1.setText("حفظ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 0));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\delete2.jpg")); // NOI18N
        jButton2.setText("حذف");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 0));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\folder_new.jpg")); // NOI18N
        jButton3.setText("جديد");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Simplified Arabic", 0, 14)); // NOI18N
        jLabel3.setText("رقم المستخدم");

        userid_txt.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pass_txt)
                            .addComponent(user_txt)
                            .addComponent(userid_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(userid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(user_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\close.png")); // NOI18N
        jMenuItem1.setText("اغلاق");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\report\\icon\\exit.jpg")); // NOI18N
        jMenuItem2.setText("الخروج من البرنامج");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1148, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        del_user();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       new_user();
    }//GEN-LAST:event_jButton3ActionPerformed
public void new_user(){
     try{
            userid_txt.setText("...");
            user_txt.setText(null);
            pass_txt.setText(null);
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,e);}
}
    private void user_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_txtActionPerformed

    private void user_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_tblMouseClicked
        // TODO add your handling code here:
        getting_data();
    }//GEN-LAST:event_user_tblMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        insert_db();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void close(){
        

        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEve­ntQueue().postEvent(winClosingEvent);
        
}
    
    public void db_show(){
        Connection c = null;
        Statement s = null;
        ResultSet rs= null;
        try{
            Class.forName("org.sqlite.JDBC");
              c = DriverManager.getConnection("jdbc:sqlite:decor.db");
              c.setAutoCommit(false);
              s=c.createStatement();
              String sql="select user as 'اسم المستخدم', pass as 'الرقم السرى' from login";
              rs=s.executeQuery(sql);
              user_tbl.setModel(DbUtils.resultSetToTableModel(rs));
              rs.close();
              s.close();
              c.commit();
              c.close();
        }catch(Exception e){JOptionPane.showMessageDialog(null, "حدث خطأ برجاء المحاوله مره اخرى او اغلاق البرنامج وتشغيله");}
        finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
       
       }
    }
    
     //getting data from jtable to jtext field and jlabel
    public void getting_data(){
        //connecting to DB
        Connection c= null;
        PreparedStatement pst=null;
        ResultSet rs=null;
        try{
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            int row=user_tbl.getSelectedRow();
            String user=(user_tbl.getModel().getValueAt(row, 0).toString());
            String pass=(user_tbl.getModel().getValueAt(row, 1).toString());
            String sql="select id,user,pass from login where user='"+user+"' and pass ='"+pass+"'";
            pst=(PreparedStatement) c.prepareStatement(sql);
            rs=pst.executeQuery(); 
            if(rs.next()){
                String useridt=rs.getString("id");
                userid_txt.setText(useridt);
                
                String usert=rs.getString("user");
                user_txt.setText(usert);
                
                String passt=rs.getString("pass");
                pass_txt.setText(passt);
                
            }
              pst.close();
              rs.close();
              c.commit();
              c.close();
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "حدث خطأ برجاء المحاوله مره اخرى او اغلاق البرنامج وتشغيله");
        }
        finally{
            try{
               
          //  rs.close();
            pst.close();
            c.commit();
            c.close();
            }catch(Exception e){}
       
       }
    }
    //insert and update 
    public void insert_db(){
        Connection c=null;
        Statement s=null;
       ResultSet rs=null;
        String usert=user_txt.getText();
        String passt=pass_txt.getText();
        String st=userid_txt.getText();
        
        try{
            
            if(st=="..."){
                            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:decor.db");
            c.setAutoCommit(false);
            s=c.createStatement();
            
                 String sql_select_user="select user from login where user='"+usert+"'";
                 rs=s.executeQuery(sql_select_user);
                 if(rs.next()){
                     JOptionPane.showMessageDialog(null,"هذا المستخدم مسجل سابقا");
                     rs.close();
                     s.close();
                     c.commit();
                     c.close();
                 }else{
            String sql="insert into login(user,pass)"+
                               " values('"+usert+"', '"+passt+"');";
            
            s.executeUpdate(sql);

           // show_details();
            //rs.close();
            s.close();
            c.commit();
            c.close();
                       db_show();}

             
            }else{
                                //update existing client

                Class.forName("org.sqlite.JDBC");
                c = DriverManager.getConnection("jdbc:sqlite:decor.db");
                c.setAutoCommit(false);
                s=c.createStatement();
                
                String sql_update="update login "
                        + "set user='"+usert+"', pass='"+passt+"'"
                        + " where id="+st+";";
                s.executeUpdate(sql_update);
            db_show();
           // rs.close();
            
            s.close();
            c.commit();
            c.close();
            }
            

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"هذا المستخدم مسجل سابقا");
           
        }
        finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
        }
        
    }
     //delete from db
   public void del_user(){
       Connection c= null;
       Statement s= null;
       String idt=userid_txt.getText();
       try{
           Class.forName("org.sqlite.JDBC");
                c = DriverManager.getConnection("jdbc:sqlite:decor.db");
                c.setAutoCommit(false);
               s=c.createStatement();
               String sql_del="delete from login where id="+idt+""; 
               s.executeUpdate(sql_del);
               s.close();
               c.commit();
               c.close();
               db_show();
           new_user();
       }catch(Exception e){JOptionPane.showMessageDialog(null, "برجى اختيار المستخدم اولا");}
       finally{
            try{
               
          //  rs.close();
            s.close();
            c.commit();
            c.close();
            }catch(Exception e){}
       
       }
   }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField pass_txt;
    private javax.swing.JTable user_tbl;
    private javax.swing.JTextField user_txt;
    private javax.swing.JLabel userid_txt;
    // End of variables declaration//GEN-END:variables
}
